// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: absences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const absenceCreate = `-- name: AbsenceCreate :one
INSERT INTO student_absences (wcode, course_id, date_from, date_to, reason, sit_in_course_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, wcode, course_id, date_from, date_to, reason, sit_in_course_id, created_at
`

type AbsenceCreateParams struct {
	Wcode         string      `json:"wcode"`
	CourseID      pgtype.UUID `json:"course_id"`
	DateFrom      pgtype.Date `json:"date_from"`
	DateTo        pgtype.Date `json:"date_to"`
	Reason        pgtype.Text `json:"reason"`
	SitInCourseID pgtype.UUID `json:"sit_in_course_id"`
}

type AbsenceCreateRow struct {
	ID            pgtype.UUID        `json:"id"`
	Wcode         string             `json:"wcode"`
	CourseID      pgtype.UUID        `json:"course_id"`
	DateFrom      pgtype.Date        `json:"date_from"`
	DateTo        pgtype.Date        `json:"date_to"`
	Reason        pgtype.Text        `json:"reason"`
	SitInCourseID pgtype.UUID        `json:"sit_in_course_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AbsenceCreate(ctx context.Context, arg AbsenceCreateParams) (AbsenceCreateRow, error) {
	row := q.db.QueryRow(ctx, absenceCreate,
		arg.Wcode,
		arg.CourseID,
		arg.DateFrom,
		arg.DateTo,
		arg.Reason,
		arg.SitInCourseID,
	)
	var i AbsenceCreateRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.CourseID,
		&i.DateFrom,
		&i.DateTo,
		&i.Reason,
		&i.SitInCourseID,
		&i.CreatedAt,
	)
	return i, err
}

const absenceList = `-- name: AbsenceList :many
SELECT sa.id, sa.wcode, sa.course_id, sa.date_from, sa.date_to, sa.reason, sa.sit_in_course_id, sa.created_at,
       c.code AS course_code, c.name AS course_name,
       sc.code AS sit_in_course_code, sc.name AS sit_in_course_name
FROM student_absences sa
JOIN courses c ON c.id = sa.course_id
LEFT JOIN courses sc ON sc.id = sa.sit_in_course_id
ORDER BY sa.created_at DESC
`

type AbsenceListRow struct {
	ID              pgtype.UUID        `json:"id"`
	Wcode           string             `json:"wcode"`
	CourseID        pgtype.UUID        `json:"course_id"`
	DateFrom        pgtype.Date        `json:"date_from"`
	DateTo          pgtype.Date        `json:"date_to"`
	Reason          pgtype.Text        `json:"reason"`
	SitInCourseID   pgtype.UUID        `json:"sit_in_course_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CourseCode      string             `json:"course_code"`
	CourseName      string             `json:"course_name"`
	SitInCourseCode pgtype.Text        `json:"sit_in_course_code"`
	SitInCourseName pgtype.Text        `json:"sit_in_course_name"`
}

func (q *Queries) AbsenceList(ctx context.Context) ([]AbsenceListRow, error) {
	rows, err := q.db.Query(ctx, absenceList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbsenceListRow
	for rows.Next() {
		var i AbsenceListRow
		if err := rows.Scan(
			&i.ID,
			&i.Wcode,
			&i.CourseID,
			&i.DateFrom,
			&i.DateTo,
			&i.Reason,
			&i.SitInCourseID,
			&i.CreatedAt,
			&i.CourseCode,
			&i.CourseName,
			&i.SitInCourseCode,
			&i.SitInCourseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const absenceOverlappingSessions = `-- name: AbsenceOverlappingSessions :many
SELECT DISTINCT sess.id AS session_id
FROM sessions sess
JOIN student_absences sa ON sa.course_id = sess.course_id
WHERE sa.wcode = $1
  AND sess.start_at >= sa.date_from
  AND sess.start_at < (sa.date_to + interval '1 day')
  AND sess.start_at >= $2
  AND sess.start_at < ($3::date + interval '1 day')
  AND sess.deleted_at IS NULL
`

type AbsenceOverlappingSessionsParams struct {
	Wcode   string             `json:"wcode"`
	StartAt pgtype.Timestamptz `json:"start_at"`
	Column3 pgtype.Date        `json:"column_3"`
}

func (q *Queries) AbsenceOverlappingSessions(ctx context.Context, arg AbsenceOverlappingSessionsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, absenceOverlappingSessions, arg.Wcode, arg.StartAt, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var session_id pgtype.UUID
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsByStudentInRange = `-- name: SessionsByStudentInRange :many
SELECT
  sess.id,
  sess.start_at,
  sess.end_at,
  c.id AS course_id,
  c.code AS course_code,
  c.name AS course_name,
  sub.id AS subject_id,
  sub.code AS subject_code,
  sub.name AS subject_name
FROM sessions sess
JOIN courses c ON c.id = sess.course_id AND c.deleted_at IS NULL
JOIN subjects sub ON sub.id = c.subject_id AND sub.deleted_at IS NULL
JOIN course_students cs ON cs.course_id = c.id AND cs.status = 'enrolled'
JOIN students st ON st.id = cs.student_id
WHERE st.wcode = $1
  AND sess.start_at >= $2
  AND sess.start_at < ($3::date + interval '1 day')
  AND sess.deleted_at IS NULL
ORDER BY sub.code, sess.start_at
`

type SessionsByStudentInRangeParams struct {
	Wcode   string             `json:"wcode"`
	StartAt pgtype.Timestamptz `json:"start_at"`
	Column3 pgtype.Date        `json:"column_3"`
}

type SessionsByStudentInRangeRow struct {
	ID          pgtype.UUID        `json:"id"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	EndAt       pgtype.Timestamptz `json:"end_at"`
	CourseID    pgtype.UUID        `json:"course_id"`
	CourseCode  string             `json:"course_code"`
	CourseName  string             `json:"course_name"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	SubjectCode string             `json:"subject_code"`
	SubjectName string             `json:"subject_name"`
}

func (q *Queries) SessionsByStudentInRange(ctx context.Context, arg SessionsByStudentInRangeParams) ([]SessionsByStudentInRangeRow, error) {
	rows, err := q.db.Query(ctx, sessionsByStudentInRange, arg.Wcode, arg.StartAt, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionsByStudentInRangeRow
	for rows.Next() {
		var i SessionsByStudentInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.StartAt,
			&i.EndAt,
			&i.CourseID,
			&i.CourseCode,
			&i.CourseName,
			&i.SubjectID,
			&i.SubjectCode,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
