// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: absences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const absenceCreate = `-- name: AbsenceCreate :one
INSERT INTO student_absences (wcode, course_id, date_from, date_to, reason, sit_in_course_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, wcode, course_id, date_from, date_to, reason, sit_in_course_id, created_at
`

type AbsenceCreateParams struct {
	Wcode         string      `json:"wcode"`
	CourseID      pgtype.UUID `json:"course_id"`
	DateFrom      pgtype.Date `json:"date_from"`
	DateTo        pgtype.Date `json:"date_to"`
	Reason        pgtype.Text `json:"reason"`
	SitInCourseID pgtype.UUID `json:"sit_in_course_id"`
}

func (q *Queries) AbsenceCreate(ctx context.Context, arg AbsenceCreateParams) (StudentAbsence, error) {
	row := q.db.QueryRow(ctx, absenceCreate,
		arg.Wcode,
		arg.CourseID,
		arg.DateFrom,
		arg.DateTo,
		arg.Reason,
		arg.SitInCourseID,
	)
	var i StudentAbsence
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.CourseID,
		&i.DateFrom,
		&i.DateTo,
		&i.Reason,
		&i.SitInCourseID,
		&i.CreatedAt,
	)
	return i, err
}

const absenceList = `-- name: AbsenceList :many
SELECT sa.id, sa.wcode, sa.course_id, sa.date_from, sa.date_to, sa.reason, sa.sit_in_course_id, sa.created_at,
       c.code AS course_code, c.name AS course_name,
       sc.code AS sit_in_course_code, sc.name AS sit_in_course_name
FROM student_absences sa
JOIN courses c ON c.id = sa.course_id
LEFT JOIN courses sc ON sc.id = sa.sit_in_course_id
ORDER BY sa.created_at DESC
`

type AbsenceListRow struct {
	ID              pgtype.UUID        `json:"id"`
	Wcode           string             `json:"wcode"`
	CourseID        pgtype.UUID        `json:"course_id"`
	DateFrom        pgtype.Date        `json:"date_from"`
	DateTo          pgtype.Date        `json:"date_to"`
	Reason          pgtype.Text        `json:"reason"`
	SitInCourseID   pgtype.UUID        `json:"sit_in_course_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CourseCode      string             `json:"course_code"`
	CourseName      string             `json:"course_name"`
	SitInCourseCode pgtype.Text        `json:"sit_in_course_code"`
	SitInCourseName pgtype.Text        `json:"sit_in_course_name"`
}

func (q *Queries) AbsenceList(ctx context.Context) ([]AbsenceListRow, error) {
	rows, err := q.db.Query(ctx, absenceList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbsenceListRow
	for rows.Next() {
		var i AbsenceListRow
		if err := rows.Scan(
			&i.ID,
			&i.Wcode,
			&i.CourseID,
			&i.DateFrom,
			&i.DateTo,
			&i.Reason,
			&i.SitInCourseID,
			&i.CreatedAt,
			&i.CourseCode,
			&i.CourseName,
			&i.SitInCourseCode,
			&i.SitInCourseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
