// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkRoomAvailability = `-- name: CheckRoomAvailability :one
SELECT EXISTS (
    SELECT 1 FROM room_availability a
    WHERE a.room_id = $1 AND a.deleted_at IS NULL
) AS has_windows,
EXISTS (
    SELECT 1 FROM room_availability a
    WHERE a.room_id = $1
      AND a.deleted_at IS NULL
      AND a.time_range @> tstzrange($2::timestamptz, $3::timestamptz, '[)')
) AS is_available
`

type CheckRoomAvailabilityParams struct {
	RoomID  pgtype.UUID        `json:"room_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

type CheckRoomAvailabilityRow struct {
	HasWindows  bool `json:"has_windows"`
	IsAvailable bool `json:"is_available"`
}

func (q *Queries) CheckRoomAvailability(ctx context.Context, arg CheckRoomAvailabilityParams) (CheckRoomAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, checkRoomAvailability, arg.RoomID, arg.Column2, arg.Column3)
	var i CheckRoomAvailabilityRow
	err := row.Scan(&i.HasWindows, &i.IsAvailable)
	return i, err
}

const checkTeacherAvailability = `-- name: CheckTeacherAvailability :one
SELECT EXISTS (
    SELECT 1 FROM teacher_availability a
    WHERE a.teacher_id = $1 AND a.deleted_at IS NULL
) AS has_windows,
EXISTS (
    SELECT 1 FROM teacher_availability a
    WHERE a.teacher_id = $1
      AND a.deleted_at IS NULL
      AND a.time_range @> tstzrange($2::timestamptz, $3::timestamptz, '[)')
) AS is_available
`

type CheckTeacherAvailabilityParams struct {
	TeacherID pgtype.UUID        `json:"teacher_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
	Column3   pgtype.Timestamptz `json:"column_3"`
}

type CheckTeacherAvailabilityRow struct {
	HasWindows  bool `json:"has_windows"`
	IsAvailable bool `json:"is_available"`
}

func (q *Queries) CheckTeacherAvailability(ctx context.Context, arg CheckTeacherAvailabilityParams) (CheckTeacherAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, checkTeacherAvailability, arg.TeacherID, arg.Column2, arg.Column3)
	var i CheckTeacherAvailabilityRow
	err := row.Scan(&i.HasWindows, &i.IsAvailable)
	return i, err
}

const createRoomAvailability = `-- name: CreateRoomAvailability :one
INSERT INTO room_availability (room_id, start_at, end_at)
VALUES ($1, $2, $3)
RETURNING id, room_id, start_at, end_at, created_at, updated_at
`

type CreateRoomAvailabilityParams struct {
	RoomID  pgtype.UUID        `json:"room_id"`
	StartAt pgtype.Timestamptz `json:"start_at"`
	EndAt   pgtype.Timestamptz `json:"end_at"`
}

type CreateRoomAvailabilityRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRoomAvailability(ctx context.Context, arg CreateRoomAvailabilityParams) (CreateRoomAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, createRoomAvailability, arg.RoomID, arg.StartAt, arg.EndAt)
	var i CreateRoomAvailabilityRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeacherAvailability = `-- name: CreateTeacherAvailability :one
INSERT INTO teacher_availability (teacher_id, start_at, end_at)
VALUES ($1, $2, $3)
RETURNING id, teacher_id, start_at, end_at, created_at, updated_at
`

type CreateTeacherAvailabilityParams struct {
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
}

type CreateTeacherAvailabilityRow struct {
	ID        pgtype.UUID        `json:"id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTeacherAvailability(ctx context.Context, arg CreateTeacherAvailabilityParams) (CreateTeacherAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, createTeacherAvailability, arg.TeacherID, arg.StartAt, arg.EndAt)
	var i CreateTeacherAvailabilityRow
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoomAvailability = `-- name: ListRoomAvailability :many

SELECT id, room_id, start_at, end_at, created_at, updated_at
FROM room_availability
WHERE room_id = $1
  AND deleted_at IS NULL
ORDER BY start_at
`

type ListRoomAvailabilityRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Room availability
func (q *Queries) ListRoomAvailability(ctx context.Context, roomID pgtype.UUID) ([]ListRoomAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listRoomAvailability, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomAvailabilityRow
	for rows.Next() {
		var i ListRoomAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomAvailabilityByRange = `-- name: ListRoomAvailabilityByRange :many
SELECT id, room_id, start_at, end_at, created_at, updated_at
FROM room_availability
WHERE room_id = $1
  AND deleted_at IS NULL
  AND time_range && tstzrange($2, $3, '[)')
ORDER BY start_at
`

type ListRoomAvailabilityByRangeParams struct {
	RoomID      pgtype.UUID `json:"room_id"`
	Tstzrange   interface{} `json:"tstzrange"`
	Tstzrange_2 interface{} `json:"tstzrange_2"`
}

type ListRoomAvailabilityByRangeRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRoomAvailabilityByRange(ctx context.Context, arg ListRoomAvailabilityByRangeParams) ([]ListRoomAvailabilityByRangeRow, error) {
	rows, err := q.db.Query(ctx, listRoomAvailabilityByRange, arg.RoomID, arg.Tstzrange, arg.Tstzrange_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomAvailabilityByRangeRow
	for rows.Next() {
		var i ListRoomAvailabilityByRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAvailability = `-- name: ListTeacherAvailability :many

SELECT id, teacher_id, start_at, end_at, created_at, updated_at
FROM teacher_availability
WHERE teacher_id = $1
  AND deleted_at IS NULL
ORDER BY start_at
`

type ListTeacherAvailabilityRow struct {
	ID        pgtype.UUID        `json:"id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Teacher availability
func (q *Queries) ListTeacherAvailability(ctx context.Context, teacherID pgtype.UUID) ([]ListTeacherAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listTeacherAvailability, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeacherAvailabilityRow
	for rows.Next() {
		var i ListTeacherAvailabilityRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeacherAvailabilityByRange = `-- name: ListTeacherAvailabilityByRange :many
SELECT id, teacher_id, start_at, end_at, created_at, updated_at
FROM teacher_availability
WHERE teacher_id = $1
  AND deleted_at IS NULL
  AND time_range && tstzrange($2, $3, '[)')
ORDER BY start_at
`

type ListTeacherAvailabilityByRangeParams struct {
	TeacherID   pgtype.UUID `json:"teacher_id"`
	Tstzrange   interface{} `json:"tstzrange"`
	Tstzrange_2 interface{} `json:"tstzrange_2"`
}

type ListTeacherAvailabilityByRangeRow struct {
	ID        pgtype.UUID        `json:"id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTeacherAvailabilityByRange(ctx context.Context, arg ListTeacherAvailabilityByRangeParams) ([]ListTeacherAvailabilityByRangeRow, error) {
	rows, err := q.db.Query(ctx, listTeacherAvailabilityByRange, arg.TeacherID, arg.Tstzrange, arg.Tstzrange_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeacherAvailabilityByRangeRow
	for rows.Next() {
		var i ListTeacherAvailabilityByRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.StartAt,
			&i.EndAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRoomAvailability = `-- name: SoftDeleteRoomAvailability :exec
UPDATE room_availability
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND room_id = $2 AND deleted_at IS NULL
`

type SoftDeleteRoomAvailabilityParams struct {
	ID     pgtype.UUID `json:"id"`
	RoomID pgtype.UUID `json:"room_id"`
}

func (q *Queries) SoftDeleteRoomAvailability(ctx context.Context, arg SoftDeleteRoomAvailabilityParams) error {
	_, err := q.db.Exec(ctx, softDeleteRoomAvailability, arg.ID, arg.RoomID)
	return err
}

const softDeleteTeacherAvailability = `-- name: SoftDeleteTeacherAvailability :exec
UPDATE teacher_availability
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND teacher_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTeacherAvailabilityParams struct {
	ID        pgtype.UUID `json:"id"`
	TeacherID pgtype.UUID `json:"teacher_id"`
}

func (q *Queries) SoftDeleteTeacherAvailability(ctx context.Context, arg SoftDeleteTeacherAvailabilityParams) error {
	_, err := q.db.Exec(ctx, softDeleteTeacherAvailability, arg.ID, arg.TeacherID)
	return err
}
