// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillAssignmentEventSnapshot = `-- name: BackfillAssignmentEventSnapshot :one
SELECT
  ase.created_at AS captured_at,
  s.version AS session_version
FROM absence_sit_in_assignment_events ase
JOIN sessions s ON s.id = ase.new_session_id
WHERE ase.absence_id = $1
  AND ase.new_session_id = $2
  AND ase.action = 'assigned'
  AND s.version = $3
ORDER BY ase.created_at DESC
LIMIT 1
`

type BackfillAssignmentEventSnapshotParams struct {
	AbsenceID    pgtype.UUID `json:"absence_id"`
	NewSessionID pgtype.UUID `json:"new_session_id"`
	Version      int32       `json:"version"`
}

type BackfillAssignmentEventSnapshotRow struct {
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
	SessionVersion int32              `json:"session_version"`
}

// Evidence source 1: Find exact assignment event with snapshot data.
func (q *Queries) BackfillAssignmentEventSnapshot(ctx context.Context, arg BackfillAssignmentEventSnapshotParams) (BackfillAssignmentEventSnapshotRow, error) {
	row := q.db.QueryRow(ctx, backfillAssignmentEventSnapshot, arg.AbsenceID, arg.NewSessionID, arg.Version)
	var i BackfillAssignmentEventSnapshotRow
	err := row.Scan(&i.CapturedAt, &i.SessionVersion)
	return i, err
}

const backfillCountEligible = `-- name: BackfillCountEligible :one
SELECT count(*)::int4 AS total
FROM absence_sit_ins
WHERE snapshot_quality = 'unavailable'
`

// Count total eligible rows for reporting.
func (q *Queries) BackfillCountEligible(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, backfillCountEligible)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const backfillEligibleAssignments = `-- name: BackfillEligibleAssignments :many
SELECT
  asi.id,
  asi.absence_id,
  asi.session_id,
  asi.session_version_at_assignment,
  asi.assigned_at,
  COALESCE(s.version, 0) AS current_session_version,
  (s.deleted_at IS NOT NULL) AS current_session_deleted
FROM absence_sit_ins asi
LEFT JOIN sessions s ON s.id = asi.session_id
WHERE asi.snapshot_quality = 'unavailable'
ORDER BY asi.assigned_at, asi.id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type BackfillEligibleAssignmentsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	AbsenceID                  pgtype.UUID        `json:"absence_id"`
	SessionID                  pgtype.UUID        `json:"session_id"`
	SessionVersionAtAssignment pgtype.Int4        `json:"session_version_at_assignment"`
	AssignedAt                 pgtype.Timestamptz `json:"assigned_at"`
	CurrentSessionVersion      int32              `json:"current_session_version"`
	CurrentSessionDeleted      interface{}        `json:"current_session_deleted"`
}

// Find absence_sit_ins rows that need backfill (snapshot is unavailable).
// Uses FOR UPDATE SKIP LOCKED for concurrent safety.
func (q *Queries) BackfillEligibleAssignments(ctx context.Context, limit int32) ([]BackfillEligibleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, backfillEligibleAssignments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackfillEligibleAssignmentsRow
	for rows.Next() {
		var i BackfillEligibleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AbsenceID,
			&i.SessionID,
			&i.SessionVersionAtAssignment,
			&i.AssignedAt,
			&i.CurrentSessionVersion,
			&i.CurrentSessionDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillSampleByQuality = `-- name: BackfillSampleByQuality :many
SELECT
  asi.id,
  asi.absence_id,
  asi.session_id,
  asi.snapshot_quality,
  asi.snapshot_source,
  asi.snapshot_captured_at,
  asi.session_snapshot_at_assignment
FROM absence_sit_ins asi
WHERE asi.snapshot_quality = $1
ORDER BY RANDOM()
LIMIT $2
`

type BackfillSampleByQualityParams struct {
	SnapshotQuality string `json:"snapshot_quality"`
	Limit           int32  `json:"limit"`
}

type BackfillSampleByQualityRow struct {
	ID                          pgtype.UUID        `json:"id"`
	AbsenceID                   pgtype.UUID        `json:"absence_id"`
	SessionID                   pgtype.UUID        `json:"session_id"`
	SnapshotQuality             string             `json:"snapshot_quality"`
	SnapshotSource              pgtype.Text        `json:"snapshot_source"`
	SnapshotCapturedAt          pgtype.Timestamptz `json:"snapshot_captured_at"`
	SessionSnapshotAtAssignment []byte             `json:"session_snapshot_at_assignment"`
}

// Sample records from each quality category for manual validation.
func (q *Queries) BackfillSampleByQuality(ctx context.Context, arg BackfillSampleByQualityParams) ([]BackfillSampleByQualityRow, error) {
	rows, err := q.db.Query(ctx, backfillSampleByQuality, arg.SnapshotQuality, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackfillSampleByQualityRow
	for rows.Next() {
		var i BackfillSampleByQualityRow
		if err := rows.Scan(
			&i.ID,
			&i.AbsenceID,
			&i.SessionID,
			&i.SnapshotQuality,
			&i.SnapshotSource,
			&i.SnapshotCapturedAt,
			&i.SessionSnapshotAtAssignment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillSessionChangeAfterSnapshot = `-- name: BackfillSessionChangeAfterSnapshot :one
SELECT
  sc.after_snapshot AS snapshot,
  sc.created_at AS captured_at
FROM session_changes sc
WHERE sc.session_id = $1
  AND sc.session_version = $2
LIMIT 1
`

type BackfillSessionChangeAfterSnapshotParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	SessionVersion int32       `json:"session_version"`
}

type BackfillSessionChangeAfterSnapshotRow struct {
	Snapshot   []byte             `json:"snapshot"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
}

// Evidence source 3b: Find session_changes where this version is the after state.
func (q *Queries) BackfillSessionChangeAfterSnapshot(ctx context.Context, arg BackfillSessionChangeAfterSnapshotParams) (BackfillSessionChangeAfterSnapshotRow, error) {
	row := q.db.QueryRow(ctx, backfillSessionChangeAfterSnapshot, arg.SessionID, arg.SessionVersion)
	var i BackfillSessionChangeAfterSnapshotRow
	err := row.Scan(&i.Snapshot, &i.CapturedAt)
	return i, err
}

const backfillSessionChangeBeforeSnapshot = `-- name: BackfillSessionChangeBeforeSnapshot :one
SELECT
  sc.before_snapshot AS snapshot,
  sc.created_at AS captured_at
FROM session_changes sc
WHERE sc.session_id = $1
  AND sc.session_version = ($2 + 1)
LIMIT 1
`

type BackfillSessionChangeBeforeSnapshotParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Column2   interface{} `json:"column_2"`
}

type BackfillSessionChangeBeforeSnapshotRow struct {
	Snapshot   []byte             `json:"snapshot"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
}

// Evidence source 3a: Find session_changes where this assignment's version was the before state.
func (q *Queries) BackfillSessionChangeBeforeSnapshot(ctx context.Context, arg BackfillSessionChangeBeforeSnapshotParams) (BackfillSessionChangeBeforeSnapshotRow, error) {
	row := q.db.QueryRow(ctx, backfillSessionChangeBeforeSnapshot, arg.SessionID, arg.Column2)
	var i BackfillSessionChangeBeforeSnapshotRow
	err := row.Scan(&i.Snapshot, &i.CapturedAt)
	return i, err
}

const backfillSessionRevisionSnapshot = `-- name: BackfillSessionRevisionSnapshot :one
SELECT
  sc.after_snapshot AS snapshot,
  sc.created_at AS captured_at
FROM session_changes sc
WHERE sc.session_id = $1
  AND sc.session_version = $2
LIMIT 1
`

type BackfillSessionRevisionSnapshotParams struct {
	SessionID      pgtype.UUID `json:"session_id"`
	SessionVersion int32       `json:"session_version"`
}

type BackfillSessionRevisionSnapshotRow struct {
	Snapshot   []byte             `json:"snapshot"`
	CapturedAt pgtype.Timestamptz `json:"captured_at"`
}

// Evidence source 2: Find session_changes record matching stored assignment version.
func (q *Queries) BackfillSessionRevisionSnapshot(ctx context.Context, arg BackfillSessionRevisionSnapshotParams) (BackfillSessionRevisionSnapshotRow, error) {
	row := q.db.QueryRow(ctx, backfillSessionRevisionSnapshot, arg.SessionID, arg.SessionVersion)
	var i BackfillSessionRevisionSnapshotRow
	err := row.Scan(&i.Snapshot, &i.CapturedAt)
	return i, err
}

const backfillUpdateSnapshot = `-- name: BackfillUpdateSnapshot :exec
UPDATE absence_sit_ins
SET
  session_snapshot_at_assignment = $2,
  snapshot_schema_version = $3,
  snapshot_captured_at = $4,
  snapshot_quality = $5,
  snapshot_source = $6
WHERE id = $1
`

type BackfillUpdateSnapshotParams struct {
	ID                          pgtype.UUID        `json:"id"`
	SessionSnapshotAtAssignment []byte             `json:"session_snapshot_at_assignment"`
	SnapshotSchemaVersion       pgtype.Int2        `json:"snapshot_schema_version"`
	SnapshotCapturedAt          pgtype.Timestamptz `json:"snapshot_captured_at"`
	SnapshotQuality             string             `json:"snapshot_quality"`
	SnapshotSource              pgtype.Text        `json:"snapshot_source"`
}

// Update a single assignment with reconstructed snapshot data.
func (q *Queries) BackfillUpdateSnapshot(ctx context.Context, arg BackfillUpdateSnapshotParams) error {
	_, err := q.db.Exec(ctx, backfillUpdateSnapshot,
		arg.ID,
		arg.SessionSnapshotAtAssignment,
		arg.SnapshotSchemaVersion,
		arg.SnapshotCapturedAt,
		arg.SnapshotQuality,
		arg.SnapshotSource,
	)
	return err
}
