// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: course_students.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseStudentAdd = `-- name: CourseStudentAdd :exec
INSERT INTO course_students (course_id, student_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CourseStudentAddParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) CourseStudentAdd(ctx context.Context, arg CourseStudentAddParams) error {
	_, err := q.db.Exec(ctx, courseStudentAdd, arg.CourseID, arg.StudentID)
	return err
}

const courseStudentAddDraft = `-- name: CourseStudentAddDraft :exec
INSERT INTO course_students (course_id, student_id, status)
VALUES ($1, $2, 'draft')
ON CONFLICT (course_id, student_id) DO NOTHING
`

type CourseStudentAddDraftParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) CourseStudentAddDraft(ctx context.Context, arg CourseStudentAddDraftParams) error {
	_, err := q.db.Exec(ctx, courseStudentAddDraft, arg.CourseID, arg.StudentID)
	return err
}

const courseStudentRemove = `-- name: CourseStudentRemove :exec
DELETE FROM course_students
WHERE course_id = $1 AND student_id = $2
`

type CourseStudentRemoveParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) CourseStudentRemove(ctx context.Context, arg CourseStudentRemoveParams) error {
	_, err := q.db.Exec(ctx, courseStudentRemove, arg.CourseID, arg.StudentID)
	return err
}

const courseStudentRemoveDraftIfStatus = `-- name: CourseStudentRemoveDraftIfStatus :execrows
DELETE FROM course_students
WHERE course_id = $1 AND student_id = $2 AND status = 'draft'
`

type CourseStudentRemoveDraftIfStatusParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) CourseStudentRemoveDraftIfStatus(ctx context.Context, arg CourseStudentRemoveDraftIfStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, courseStudentRemoveDraftIfStatus, arg.CourseID, arg.StudentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const courseStudentRemoveDraftsByIDs = `-- name: CourseStudentRemoveDraftsByIDs :execrows
DELETE FROM course_students
WHERE course_id = $1 AND student_id = ANY($2::uuid[]) AND status = 'draft'
`

type CourseStudentRemoveDraftsByIDsParams struct {
	CourseID pgtype.UUID   `json:"course_id"`
	Column2  []pgtype.UUID `json:"column_2"`
}

func (q *Queries) CourseStudentRemoveDraftsByIDs(ctx context.Context, arg CourseStudentRemoveDraftsByIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, courseStudentRemoveDraftsByIDs, arg.CourseID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const courseStudentUpdateStatus = `-- name: CourseStudentUpdateStatus :exec
UPDATE course_students
SET status = $3
WHERE course_id = $1 AND student_id = $2
`

type CourseStudentUpdateStatusParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	StudentID pgtype.UUID `json:"student_id"`
	Status    string      `json:"status"`
}

func (q *Queries) CourseStudentUpdateStatus(ctx context.Context, arg CourseStudentUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, courseStudentUpdateStatus, arg.CourseID, arg.StudentID, arg.Status)
	return err
}

const courseStudentUpdateStatusRow = `-- name: CourseStudentUpdateStatusRow :execrows
UPDATE course_students
SET status = $3
WHERE course_id = $1 AND student_id = $2 AND status = $4
`

type CourseStudentUpdateStatusRowParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	StudentID pgtype.UUID `json:"student_id"`
	NewStatus string      `json:"new_status"`
	OldStatus string      `json:"old_status"`
}

func (q *Queries) CourseStudentUpdateStatusRow(ctx context.Context, arg CourseStudentUpdateStatusRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, courseStudentUpdateStatusRow,
		arg.CourseID,
		arg.StudentID,
		arg.NewStatus,
		arg.OldStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const courseStudentsList = `-- name: CourseStudentsList :many
SELECT student_id, created_at
FROM course_students
WHERE course_id = $1
ORDER BY created_at ASC
`

type CourseStudentsListRow struct {
	StudentID pgtype.UUID        `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CourseStudentsList(ctx context.Context, courseID pgtype.UUID) ([]CourseStudentsListRow, error) {
	rows, err := q.db.Query(ctx, courseStudentsList, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseStudentsListRow
	for rows.Next() {
		var i CourseStudentsListRow
		if err := rows.Scan(&i.StudentID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseStudentsListDetailed = `-- name: CourseStudentsListDetailed :many
SELECT s.id, s.wcode, s.full_name, s.notes, s.created_at, s.updated_at
FROM course_students cs
JOIN students s ON s.id = cs.student_id
WHERE cs.course_id = $1
ORDER BY s.wcode ASC
`

func (q *Queries) CourseStudentsListDetailed(ctx context.Context, courseID pgtype.UUID) ([]Student, error) {
	rows, err := q.db.Query(ctx, courseStudentsListDetailed, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.Wcode,
			&i.FullName,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseStudentsListDetailedWithStatus = `-- name: CourseStudentsListDetailedWithStatus :many
SELECT s.id, s.wcode, s.full_name, s.notes, s.created_at, s.updated_at,
       cs.status
FROM course_students cs
JOIN students s ON s.id = cs.student_id
WHERE cs.course_id = $1
ORDER BY s.wcode ASC
`

type CourseStudentsListDetailedWithStatusRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Status    string             `json:"status"`
}

func (q *Queries) CourseStudentsListDetailedWithStatus(ctx context.Context, courseID pgtype.UUID) ([]CourseStudentsListDetailedWithStatusRow, error) {
	rows, err := q.db.Query(ctx, courseStudentsListDetailedWithStatus, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseStudentsListDetailedWithStatusRow
	for rows.Next() {
		var i CourseStudentsListDetailedWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Wcode,
			&i.FullName,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
