// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseCreate = `-- name: CourseCreate :one
INSERT INTO courses (code, name)
VALUES ($1, $2)
RETURNING id, code, name, deleted_at, created_at, updated_at
`

type CourseCreateParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type CourseCreateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CourseCreate(ctx context.Context, arg CourseCreateParams) (CourseCreateRow, error) {
	row := q.db.QueryRow(ctx, courseCreate, arg.Code, arg.Name)
	var i CourseCreateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const courseGetByID = `-- name: CourseGetByID :one
SELECT id, code, name, deleted_at, created_at, updated_at
FROM courses
WHERE id = $1
`

type CourseGetByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CourseGetByID(ctx context.Context, id pgtype.UUID) (CourseGetByIDRow, error) {
	row := q.db.QueryRow(ctx, courseGetByID, id)
	var i CourseGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const courseListActive = `-- name: CourseListActive :many
SELECT id, code, name, deleted_at, created_at, updated_at
FROM courses
WHERE deleted_at IS NULL
ORDER BY code ASC
`

type CourseListActiveRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CourseListActive(ctx context.Context) ([]CourseListActiveRow, error) {
	rows, err := q.db.Query(ctx, courseListActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseListActiveRow
	for rows.Next() {
		var i CourseListActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseRestore = `-- name: CourseRestore :exec
UPDATE courses
SET deleted_at = NULL, updated_at = now()
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) CourseRestore(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, courseRestore, id)
	return err
}

const courseSoftDelete = `-- name: CourseSoftDelete :exec
UPDATE courses
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) CourseSoftDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, courseSoftDelete, id)
	return err
}

const courseUpdate = `-- name: CourseUpdate :one
UPDATE courses
SET code = $2, name = $3, updated_at = now()
WHERE id = $1
RETURNING id, code, name, deleted_at, created_at, updated_at
`

type CourseUpdateParams struct {
	ID   pgtype.UUID `json:"id"`
	Code string      `json:"code"`
	Name string      `json:"name"`
}

type CourseUpdateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CourseUpdate(ctx context.Context, arg CourseUpdateParams) (CourseUpdateRow, error) {
	row := q.db.QueryRow(ctx, courseUpdate, arg.ID, arg.Code, arg.Name)
	var i CourseUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
