// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseCreate = `-- name: CourseCreate :one
INSERT INTO courses (code, name)
VALUES ($1, $2)
RETURNING id, code, name, created_at, updated_at
`

type CourseCreateParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type CourseCreateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CourseCreate(ctx context.Context, arg CourseCreateParams) (CourseCreateRow, error) {
	row := q.db.QueryRow(ctx, courseCreate, arg.Code, arg.Name)
	var i CourseCreateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const courseDelete = `-- name: CourseDelete :exec
DELETE FROM courses
WHERE id = $1
`

func (q *Queries) CourseDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, courseDelete, id)
	return err
}

const courseGetByID = `-- name: CourseGetByID :one
SELECT id, code, name, created_at, updated_at
FROM courses
WHERE id = $1
`

type CourseGetByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CourseGetByID(ctx context.Context, id pgtype.UUID) (CourseGetByIDRow, error) {
	row := q.db.QueryRow(ctx, courseGetByID, id)
	var i CourseGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const courseGetCoreByID = `-- name: CourseGetCoreByID :one
SELECT id, version, code, name, teacher_id
FROM courses
WHERE id = $1
`

type CourseGetCoreByIDRow struct {
	ID        pgtype.UUID `json:"id"`
	Version   int32       `json:"version"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	TeacherID pgtype.UUID `json:"teacher_id"`
}

func (q *Queries) CourseGetCoreByID(ctx context.Context, id pgtype.UUID) (CourseGetCoreByIDRow, error) {
	row := q.db.QueryRow(ctx, courseGetCoreByID, id)
	var i CourseGetCoreByIDRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Code,
		&i.Name,
		&i.TeacherID,
	)
	return i, err
}

const courseListActive = `-- name: CourseListActive :many
SELECT c.id, c.code, c.name, COALESCE(s.name, '') AS subject_name, c.created_at, c.updated_at
FROM courses c
LEFT JOIN subjects s ON s.id = c.subject_id
ORDER BY c.code ASC
`

type CourseListActiveRow struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	SubjectName string             `json:"subject_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CourseListActive(ctx context.Context) ([]CourseListActiveRow, error) {
	rows, err := q.db.Query(ctx, courseListActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseListActiveRow
	for rows.Next() {
		var i CourseListActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.SubjectName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
