// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: course_teachers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const courseCreateAggregate = `-- name: CourseCreateAggregate :one
UPDATE courses
SET
    code = $2,
    name = $3,
    legacy_course_id = $4,
    teacher_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, version
`

type CourseCreateAggregateParams struct {
	ID             pgtype.UUID `json:"id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	LegacyCourseID pgtype.Text `json:"legacy_course_id"`
	TeacherID      pgtype.UUID `json:"teacher_id"`
}

type CourseCreateAggregateRow struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

// Mirror of CourseUpdateAggregate for freshly created courses: sets the
// compat primary projection (courses.teacher_id) and code/name/legacy link
// WITHOUT bumping version, so a new course starts at version 1 and the first
// edit is the first optimistic-concurrency bump.
func (q *Queries) CourseCreateAggregate(ctx context.Context, arg CourseCreateAggregateParams) (CourseCreateAggregateRow, error) {
	row := q.db.QueryRow(ctx, courseCreateAggregate,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.LegacyCourseID,
		arg.TeacherID,
	)
	var i CourseCreateAggregateRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const courseFutureSessionUsageByTeachers = `-- name: CourseFutureSessionUsageByTeachers :many
SELECT
    s.teacher_id,
    count(*) AS session_count,
    min(s.start_at)::timestamptz AS earliest_start_at,
    ((array_agg(s.id ORDER BY s.start_at, s.id))[:10])::uuid[] AS sample_session_ids,
    array_remove(array_agg(DISTINCT s.series_id), NULL)::uuid[] AS series_ids
FROM sessions s
WHERE s.course_id = $1
  AND s.teacher_id = ANY($2::uuid[])
  AND s.start_at > $3
  AND s.deleted_at IS NULL
GROUP BY s.teacher_id
`

type CourseFutureSessionUsageByTeachersParams struct {
	CourseID   pgtype.UUID        `json:"course_id"`
	TeacherIds []pgtype.UUID      `json:"teacher_ids"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
}

type CourseFutureSessionUsageByTeachersRow struct {
	TeacherID        pgtype.UUID        `json:"teacher_id"`
	SessionCount     int64              `json:"session_count"`
	EarliestStartAt  pgtype.Timestamptz `json:"earliest_start_at"`
	SampleSessionIds []pgtype.UUID      `json:"sample_session_ids"`
	SeriesIds        []pgtype.UUID      `json:"series_ids"`
}

func (q *Queries) CourseFutureSessionUsageByTeachers(ctx context.Context, arg CourseFutureSessionUsageByTeachersParams) ([]CourseFutureSessionUsageByTeachersRow, error) {
	rows, err := q.db.Query(ctx, courseFutureSessionUsageByTeachers, arg.CourseID, arg.TeacherIds, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseFutureSessionUsageByTeachersRow
	for rows.Next() {
		var i CourseFutureSessionUsageByTeachersRow
		if err := rows.Scan(
			&i.TeacherID,
			&i.SessionCount,
			&i.EarliestStartAt,
			&i.SampleSessionIds,
			&i.SeriesIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseLockForTeacherUpdate = `-- name: CourseLockForTeacherUpdate :one

SELECT
    id,
    version
FROM courses
WHERE id = $1
FOR UPDATE
`

type CourseLockForTeacherUpdateRow struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

// Course teacher membership queries for the courseadmin domain service.
// The entire teacher set of a course is replaced atomically inside one
// transaction (delete-all + reinsert), so reads here are either row locks
// or snapshots taken inside the same transaction.
func (q *Queries) CourseLockForTeacherUpdate(ctx context.Context, id pgtype.UUID) (CourseLockForTeacherUpdateRow, error) {
	row := q.db.QueryRow(ctx, courseLockForTeacherUpdate, id)
	var i CourseLockForTeacherUpdateRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const courseTeacherInsert = `-- name: CourseTeacherInsert :exec
INSERT INTO course_teachers (
    course_id,
    teacher_id,
    is_primary
)
VALUES ($1, $2, $3)
`

type CourseTeacherInsertParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	TeacherID pgtype.UUID `json:"teacher_id"`
	IsPrimary bool        `json:"is_primary"`
}

func (q *Queries) CourseTeacherInsert(ctx context.Context, arg CourseTeacherInsertParams) error {
	_, err := q.db.Exec(ctx, courseTeacherInsert, arg.CourseID, arg.TeacherID, arg.IsPrimary)
	return err
}

const courseTeachersDeleteAll = `-- name: CourseTeachersDeleteAll :exec
DELETE FROM course_teachers
WHERE course_id = $1
`

func (q *Queries) CourseTeachersDeleteAll(ctx context.Context, courseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, courseTeachersDeleteAll, courseID)
	return err
}

const courseTeachersList = `-- name: CourseTeachersList :many
SELECT
    ct.course_id,
    ct.teacher_id,
    ct.is_primary,
    u.username
FROM course_teachers ct
JOIN users u ON u.id = ct.teacher_id
WHERE ct.course_id = $1
ORDER BY
    ct.is_primary DESC,
    u.username,
    ct.teacher_id
`

type CourseTeachersListRow struct {
	CourseID  pgtype.UUID `json:"course_id"`
	TeacherID pgtype.UUID `json:"teacher_id"`
	IsPrimary bool        `json:"is_primary"`
	Username  string      `json:"username"`
}

func (q *Queries) CourseTeachersList(ctx context.Context, courseID pgtype.UUID) ([]CourseTeachersListRow, error) {
	rows, err := q.db.Query(ctx, courseTeachersList, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseTeachersListRow
	for rows.Next() {
		var i CourseTeachersListRow
		if err := rows.Scan(
			&i.CourseID,
			&i.TeacherID,
			&i.IsPrimary,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const courseUpdateAggregate = `-- name: CourseUpdateAggregate :one
UPDATE courses
SET
    code = $2,
    name = $3,
    legacy_course_id = $4,
    teacher_id = $5,
    version = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, version
`

type CourseUpdateAggregateParams struct {
	ID             pgtype.UUID `json:"id"`
	Code           string      `json:"code"`
	Name           string      `json:"name"`
	LegacyCourseID pgtype.Text `json:"legacy_course_id"`
	TeacherID      pgtype.UUID `json:"teacher_id"`
}

type CourseUpdateAggregateRow struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) CourseUpdateAggregate(ctx context.Context, arg CourseUpdateAggregateParams) (CourseUpdateAggregateRow, error) {
	row := q.db.QueryRow(ctx, courseUpdateAggregate,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.LegacyCourseID,
		arg.TeacherID,
	)
	var i CourseUpdateAggregateRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const usersListForTeacherValidation = `-- name: UsersListForTeacherValidation :many
SELECT
    id,
    username,
    role,
    deleted_at
FROM users
WHERE id = ANY($1::uuid[])
`

type UsersListForTeacherValidationRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UsersListForTeacherValidation(ctx context.Context, dollar_1 []pgtype.UUID) ([]UsersListForTeacherValidationRow, error) {
	rows, err := q.db.Query(ctx, usersListForTeacherValidation, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersListForTeacherValidationRow
	for rows.Next() {
		var i UsersListForTeacherValidationRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
