// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: crm_rows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const crmDistinctOptions = `-- name: CrmDistinctOptions :one
SELECT
  COALESCE(jsonb_agg(DISTINCT cycle_label ORDER BY cycle_label) FILTER (WHERE cycle_label IS NOT NULL), '[]'::jsonb) AS cycle_labels,
  COALESCE(jsonb_agg(DISTINCT course_name ORDER BY course_name) FILTER (WHERE course_name IS NOT NULL), '[]'::jsonb) AS course_names,
  COALESCE(jsonb_agg(DISTINCT academic_level ORDER BY academic_level) FILTER (WHERE academic_level IS NOT NULL AND btrim(academic_level) <> ''), '[]'::jsonb) AS academic_levels,
  COALESCE(jsonb_agg(DISTINCT secondary_school ORDER BY secondary_school) FILTER (WHERE secondary_school IS NOT NULL AND btrim(secondary_school) <> ''), '[]'::jsonb) AS secondary_schools
FROM crm_rows
WHERE snapshot_id = $1
`

type CrmDistinctOptionsRow struct {
	CycleLabels      interface{} `json:"cycle_labels"`
	CourseNames      interface{} `json:"course_names"`
	AcademicLevels   interface{} `json:"academic_levels"`
	SecondarySchools interface{} `json:"secondary_schools"`
}

func (q *Queries) CrmDistinctOptions(ctx context.Context, snapshotID pgtype.UUID) (CrmDistinctOptionsRow, error) {
	row := q.db.QueryRow(ctx, crmDistinctOptions, snapshotID)
	var i CrmDistinctOptionsRow
	err := row.Scan(
		&i.CycleLabels,
		&i.CourseNames,
		&i.AcademicLevels,
		&i.SecondarySchools,
	)
	return i, err
}

const crmRowsCount = `-- name: CrmRowsCount :one
SELECT COUNT(*)::bigint FROM crm_rows
`

func (q *Queries) CrmRowsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, crmRowsCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const crmRowsDeleteAll = `-- name: CrmRowsDeleteAll :exec
DELETE FROM crm_rows
`

func (q *Queries) CrmRowsDeleteAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, crmRowsDeleteAll)
	return err
}

const crmRowsInsert = `-- name: CrmRowsInsert :one
INSERT INTO crm_rows (
  row_hash, cycle_label, course_name, wcode,
  first_name, last_name, nickname, secondary_school, academic_level,
  mobile_phone, hours, teachers_raw, primary_email,
  parent_name, parent_phone, parent_email, order_quote_updated_at
) VALUES (
  $1,$2,$3,$4,
  NULLIF($5,''),NULLIF($6,''),NULLIF($7,''),NULLIF($8,''),NULLIF($9,''),
  NULLIF($10,''),$11,NULLIF($12,''),NULLIF($13,''),
  NULLIF($14,''),NULLIF($15,''),NULLIF($16,''),$17
) RETURNING row_hash
`

type CrmRowsInsertParams struct {
	RowHash             string             `json:"row_hash"`
	CycleLabel          string             `json:"cycle_label"`
	CourseName          string             `json:"course_name"`
	Wcode               string             `json:"wcode"`
	Column5             interface{}        `json:"column_5"`
	Column6             interface{}        `json:"column_6"`
	Column7             interface{}        `json:"column_7"`
	Column8             interface{}        `json:"column_8"`
	Column9             interface{}        `json:"column_9"`
	Column10            interface{}        `json:"column_10"`
	Hours               pgtype.Int4        `json:"hours"`
	Column12            interface{}        `json:"column_12"`
	Column13            interface{}        `json:"column_13"`
	Column14            interface{}        `json:"column_14"`
	Column15            interface{}        `json:"column_15"`
	Column16            interface{}        `json:"column_16"`
	OrderQuoteUpdatedAt pgtype.Timestamptz `json:"order_quote_updated_at"`
}

func (q *Queries) CrmRowsInsert(ctx context.Context, arg CrmRowsInsertParams) (string, error) {
	row := q.db.QueryRow(ctx, crmRowsInsert,
		arg.RowHash,
		arg.CycleLabel,
		arg.CourseName,
		arg.Wcode,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Hours,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
		arg.OrderQuoteUpdatedAt,
	)
	var row_hash string
	err := row.Scan(&row_hash)
	return row_hash, err
}
