// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crm_cycles.sql

package db

import (
	"context"
)

const crmCycleUpsert = `-- name: CrmCycleUpsert :one
INSERT INTO crm_cycles (id, label)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET label = EXCLUDED.label,
    updated_at = now()
RETURNING id, label, last_imported_at, created_at, updated_at
`

type CrmCycleUpsertParams struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

func (q *Queries) CrmCycleUpsert(ctx context.Context, arg CrmCycleUpsertParams) (CrmCycle, error) {
	row := q.db.QueryRow(ctx, crmCycleUpsert, arg.ID, arg.Label)
	var i CrmCycle
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.LastImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const crmCyclesDeleteUnused = `-- name: CrmCyclesDeleteUnused :exec
DELETE FROM crm_cycles
WHERE id NOT IN (SELECT DISTINCT cycle_label FROM crm_rows)
`

func (q *Queries) CrmCyclesDeleteUnused(ctx context.Context) error {
	_, err := q.db.Exec(ctx, crmCyclesDeleteUnused)
	return err
}

const crmCyclesList = `-- name: CrmCyclesList :many
SELECT id, label, last_imported_at, created_at, updated_at
FROM crm_cycles
ORDER BY label ASC
`

func (q *Queries) CrmCyclesList(ctx context.Context) ([]CrmCycle, error) {
	rows, err := q.db.Query(ctx, crmCyclesList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCycle
	for rows.Next() {
		var i CrmCycle
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.LastImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const crmCyclesUpsertFromUpload = `-- name: CrmCyclesUpsertFromUpload :exec
WITH distinct_cycles AS (
  SELECT DISTINCT cycle_label AS label FROM crm_rows
),
upserted AS (
  INSERT INTO crm_cycles (id, label)
  SELECT label, label FROM distinct_cycles
  ON CONFLICT (id) DO UPDATE
  SET label = EXCLUDED.label,
      updated_at = now()
  RETURNING id
)
UPDATE crm_cycles SET last_imported_at = now()
WHERE id IN (SELECT id FROM upserted)
`

// Upsert all distinct cycle values from uploaded rows; update last_imported_at.
func (q *Queries) CrmCyclesUpsertFromUpload(ctx context.Context) error {
	_, err := q.db.Exec(ctx, crmCyclesUpsertFromUpload)
	return err
}
