// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: legacy_sync.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeEventInsert = `-- name: ChangeEventInsert :one
INSERT INTO legacy_change_events (source_event_key, detector, entity_type, external_id, action, observed_at, raw_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7::text::jsonb)
RETURNING id, source_event_key, detector, entity_type, external_id, action, observed_at, raw_payload, status, processed_at, last_error, created_at
`

type ChangeEventInsertParams struct {
	SourceEventKey string             `json:"source_event_key"`
	Detector       string             `json:"detector"`
	EntityType     pgtype.Text        `json:"entity_type"`
	ExternalID     pgtype.Text        `json:"external_id"`
	Action         pgtype.Text        `json:"action"`
	ObservedAt     pgtype.Timestamptz `json:"observed_at"`
	RawPayload     string             `json:"raw_payload"`
}

func (q *Queries) ChangeEventInsert(ctx context.Context, arg ChangeEventInsertParams) (LegacyChangeEvent, error) {
	row := q.db.QueryRow(ctx, changeEventInsert,
		arg.SourceEventKey,
		arg.Detector,
		arg.EntityType,
		arg.ExternalID,
		arg.Action,
		arg.ObservedAt,
		arg.RawPayload,
	)
	var i LegacyChangeEvent
	err := row.Scan(
		&i.ID,
		&i.SourceEventKey,
		&i.Detector,
		&i.EntityType,
		&i.ExternalID,
		&i.Action,
		&i.ObservedAt,
		&i.RawPayload,
		&i.Status,
		&i.ProcessedAt,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const conflictCountOpen = `-- name: ConflictCountOpen :one
SELECT count(*)::int FROM legacy_sync_conflicts
WHERE status = 'open'
`

func (q *Queries) ConflictCountOpen(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, conflictCountOpen)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const conflictGet = `-- name: ConflictGet :one
SELECT id, entity_type, external_id, conflict_type, category, source_payload, local_payload, message, status, created_at, resolved_at FROM legacy_sync_conflicts
WHERE id = $1
`

func (q *Queries) ConflictGet(ctx context.Context, id pgtype.UUID) (LegacySyncConflict, error) {
	row := q.db.QueryRow(ctx, conflictGet, id)
	var i LegacySyncConflict
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.ExternalID,
		&i.ConflictType,
		&i.Category,
		&i.SourcePayload,
		&i.LocalPayload,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const conflictInsert = `-- name: ConflictInsert :one
INSERT INTO legacy_sync_conflicts (entity_type, external_id, conflict_type, category, source_payload, local_payload, message)
SELECT $1, $2, $3, $4, $5::text::jsonb, $6::text::jsonb, $7
WHERE NOT EXISTS (
    SELECT 1 FROM legacy_sync_conflicts
    WHERE entity_type = $1 AND external_id = $2
      AND conflict_type = $3 AND status = 'open'
)
RETURNING id, entity_type, external_id, conflict_type, category, source_payload, local_payload, message, status, created_at, resolved_at
`

type ConflictInsertParams struct {
	EntityType    string      `json:"entity_type"`
	ExternalID    string      `json:"external_id"`
	ConflictType  string      `json:"conflict_type"`
	Category      string      `json:"category"`
	SourcePayload string      `json:"source_payload"`
	LocalPayload  string      `json:"local_payload"`
	Message       pgtype.Text `json:"message"`
}

func (q *Queries) ConflictInsert(ctx context.Context, arg ConflictInsertParams) (LegacySyncConflict, error) {
	row := q.db.QueryRow(ctx, conflictInsert,
		arg.EntityType,
		arg.ExternalID,
		arg.ConflictType,
		arg.Category,
		arg.SourcePayload,
		arg.LocalPayload,
		arg.Message,
	)
	var i LegacySyncConflict
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.ExternalID,
		&i.ConflictType,
		&i.Category,
		&i.SourcePayload,
		&i.LocalPayload,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const conflictListOpen = `-- name: ConflictListOpen :many
SELECT id, entity_type, external_id, conflict_type, category, source_payload, local_payload, message, status, created_at, resolved_at FROM legacy_sync_conflicts
WHERE status = 'open'
ORDER BY created_at DESC
`

func (q *Queries) ConflictListOpen(ctx context.Context) ([]LegacySyncConflict, error) {
	rows, err := q.db.Query(ctx, conflictListOpen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegacySyncConflict
	for rows.Next() {
		var i LegacySyncConflict
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.ExternalID,
			&i.ConflictType,
			&i.Category,
			&i.SourcePayload,
			&i.LocalPayload,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conflictListOpenPaginated = `-- name: ConflictListOpenPaginated :many
SELECT id, entity_type, external_id, conflict_type, category, message, status, created_at, resolved_at
FROM legacy_sync_conflicts
WHERE status = 'open'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ConflictListOpenPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ConflictListOpenPaginatedRow struct {
	ID           pgtype.UUID        `json:"id"`
	EntityType   string             `json:"entity_type"`
	ExternalID   string             `json:"external_id"`
	ConflictType string             `json:"conflict_type"`
	Category     string             `json:"category"`
	Message      pgtype.Text        `json:"message"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ResolvedAt   pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) ConflictListOpenPaginated(ctx context.Context, arg ConflictListOpenPaginatedParams) ([]ConflictListOpenPaginatedRow, error) {
	rows, err := q.db.Query(ctx, conflictListOpenPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConflictListOpenPaginatedRow
	for rows.Next() {
		var i ConflictListOpenPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.ExternalID,
			&i.ConflictType,
			&i.Category,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const conflictSetStatus = `-- name: ConflictSetStatus :one
UPDATE legacy_sync_conflicts
SET status = $2, resolved_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, entity_type, external_id, conflict_type, category, source_payload, local_payload, message, status, created_at, resolved_at
`

type ConflictSetStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) ConflictSetStatus(ctx context.Context, arg ConflictSetStatusParams) (LegacySyncConflict, error) {
	row := q.db.QueryRow(ctx, conflictSetStatus, arg.ID, arg.Status)
	var i LegacySyncConflict
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.ExternalID,
		&i.ConflictType,
		&i.Category,
		&i.SourcePayload,
		&i.LocalPayload,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const deadLetterInsert = `-- name: DeadLetterInsert :one
INSERT INTO legacy_sync_dead_letters (job_type, unique_key, entity_type, external_id, payload, error_category, last_error, attempts)
VALUES ($1, $2, $3, $4, $5::text::jsonb, $6, $7, $8)
RETURNING id, job_type, unique_key, entity_type, external_id, payload, error_category, last_error, attempts, created_at
`

type DeadLetterInsertParams struct {
	JobType       string      `json:"job_type"`
	UniqueKey     pgtype.Text `json:"unique_key"`
	EntityType    pgtype.Text `json:"entity_type"`
	ExternalID    pgtype.Text `json:"external_id"`
	Payload       string      `json:"payload"`
	ErrorCategory pgtype.Text `json:"error_category"`
	LastError     string      `json:"last_error"`
	Attempts      int32       `json:"attempts"`
}

func (q *Queries) DeadLetterInsert(ctx context.Context, arg DeadLetterInsertParams) (LegacySyncDeadLetter, error) {
	row := q.db.QueryRow(ctx, deadLetterInsert,
		arg.JobType,
		arg.UniqueKey,
		arg.EntityType,
		arg.ExternalID,
		arg.Payload,
		arg.ErrorCategory,
		arg.LastError,
		arg.Attempts,
	)
	var i LegacySyncDeadLetter
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.UniqueKey,
		&i.EntityType,
		&i.ExternalID,
		&i.Payload,
		&i.ErrorCategory,
		&i.LastError,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const externalRefGet = `-- name: ExternalRefGet :one
SELECT source, entity_type, external_id, internal_id, source_hash, first_seen_at, last_seen_at, last_applied_at, last_generation, state FROM external_refs
WHERE source = $1 AND entity_type = $2 AND external_id = $3
`

type ExternalRefGetParams struct {
	Source     string `json:"source"`
	EntityType string `json:"entity_type"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) ExternalRefGet(ctx context.Context, arg ExternalRefGetParams) (ExternalRef, error) {
	row := q.db.QueryRow(ctx, externalRefGet, arg.Source, arg.EntityType, arg.ExternalID)
	var i ExternalRef
	err := row.Scan(
		&i.Source,
		&i.EntityType,
		&i.ExternalID,
		&i.InternalID,
		&i.SourceHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastAppliedAt,
		&i.LastGeneration,
		&i.State,
	)
	return i, err
}

const externalRefListByInternalID = `-- name: ExternalRefListByInternalID :many
SELECT source, entity_type, external_id, internal_id, source_hash, first_seen_at, last_seen_at, last_applied_at, last_generation, state FROM external_refs
WHERE internal_id = $1
ORDER BY source, entity_type, external_id
`

func (q *Queries) ExternalRefListByInternalID(ctx context.Context, internalID pgtype.UUID) ([]ExternalRef, error) {
	rows, err := q.db.Query(ctx, externalRefListByInternalID, internalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalRef
	for rows.Next() {
		var i ExternalRef
		if err := rows.Scan(
			&i.Source,
			&i.EntityType,
			&i.ExternalID,
			&i.InternalID,
			&i.SourceHash,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastAppliedAt,
			&i.LastGeneration,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const externalRefSetState = `-- name: ExternalRefSetState :exec
UPDATE external_refs
SET state = $4
WHERE source = $1 AND entity_type = $2 AND external_id = $3
`

type ExternalRefSetStateParams struct {
	Source     string `json:"source"`
	EntityType string `json:"entity_type"`
	ExternalID string `json:"external_id"`
	State      string `json:"state"`
}

func (q *Queries) ExternalRefSetState(ctx context.Context, arg ExternalRefSetStateParams) error {
	_, err := q.db.Exec(ctx, externalRefSetState,
		arg.Source,
		arg.EntityType,
		arg.ExternalID,
		arg.State,
	)
	return err
}

const externalRefTouchSeen = `-- name: ExternalRefTouchSeen :exec
UPDATE external_refs
SET last_seen_at = now()
WHERE source = $1 AND entity_type = $2 AND external_id = $3
`

type ExternalRefTouchSeenParams struct {
	Source     string `json:"source"`
	EntityType string `json:"entity_type"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) ExternalRefTouchSeen(ctx context.Context, arg ExternalRefTouchSeenParams) error {
	_, err := q.db.Exec(ctx, externalRefTouchSeen, arg.Source, arg.EntityType, arg.ExternalID)
	return err
}

const externalRefUpsert = `-- name: ExternalRefUpsert :one
INSERT INTO external_refs (source, entity_type, external_id, internal_id, source_hash, state)
VALUES ($1, $2, $3, $4, $5, 'active')
ON CONFLICT (source, entity_type, external_id)
DO UPDATE SET
    internal_id = EXCLUDED.internal_id,
    source_hash = EXCLUDED.source_hash,
    last_seen_at = now(),
    -- Reapplying a tombstoned reference reactivates it: the source row is
    -- back, so the mapping must not stay in a missing/tombstoned state.
    state = 'active'
RETURNING source, entity_type, external_id, internal_id, source_hash, first_seen_at, last_seen_at, last_applied_at, last_generation, state
`

type ExternalRefUpsertParams struct {
	Source     string      `json:"source"`
	EntityType string      `json:"entity_type"`
	ExternalID string      `json:"external_id"`
	InternalID pgtype.UUID `json:"internal_id"`
	SourceHash pgtype.Text `json:"source_hash"`
}

func (q *Queries) ExternalRefUpsert(ctx context.Context, arg ExternalRefUpsertParams) (ExternalRef, error) {
	row := q.db.QueryRow(ctx, externalRefUpsert,
		arg.Source,
		arg.EntityType,
		arg.ExternalID,
		arg.InternalID,
		arg.SourceHash,
	)
	var i ExternalRef
	err := row.Scan(
		&i.Source,
		&i.EntityType,
		&i.ExternalID,
		&i.InternalID,
		&i.SourceHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastAppliedAt,
		&i.LastGeneration,
		&i.State,
	)
	return i, err
}

const legacyJobClaim = `-- name: LegacyJobClaim :one
WITH candidate AS (
    SELECT j.id
    FROM legacy_sync_jobs j
    WHERE (j.status = 'queued' AND j.run_after <= now())
       OR (j.status = 'running' AND j.locked_until < now())
    ORDER BY CASE WHEN j.job_type = 'legacy_refresh_course'
                       AND EXISTS (
                           SELECT 1
                           FROM courses c
                           JOIN subject_active_courses sac
                             ON sac.subject_id = c.subject_id AND sac.course_id = c.id
                           WHERE c.legacy_course_id = j.external_id
                             AND c.absence_form_visible
                       )
                  THEN 0 ELSE 1 END,
             j.priority ASC,
             j.created_at ASC
    FOR UPDATE OF j SKIP LOCKED
    LIMIT 1
)
UPDATE legacy_sync_jobs j
SET status = 'running',
    locked_by = $1,
    locked_until = now() + ($2 * interval '1 second'),
    heartbeat_at = now(),
    attempt = j.attempt + 1,
    updated_at = now()
FROM candidate
WHERE j.id = candidate.id
RETURNING j.id, j.job_type, j.entity_type, j.external_id, j.payload, j.unique_key, j.priority, j.status, j.deadline_at, j.attempt, j.max_attempts, j.locked_by, j.locked_until, j.heartbeat_at, j.run_after, j.last_error, j.created_at, j.updated_at
`

type LegacyJobClaimParams struct {
	WorkerID     pgtype.Text `json:"worker_id"`
	LeaseSeconds interface{} `json:"lease_seconds"`
}

func (q *Queries) LegacyJobClaim(ctx context.Context, arg LegacyJobClaimParams) (LegacySyncJob, error) {
	row := q.db.QueryRow(ctx, legacyJobClaim, arg.WorkerID, arg.LeaseSeconds)
	var i LegacySyncJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.EntityType,
		&i.ExternalID,
		&i.Payload,
		&i.UniqueKey,
		&i.Priority,
		&i.Status,
		&i.DeadlineAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.HeartbeatAt,
		&i.RunAfter,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const legacyJobComplete = `-- name: LegacyJobComplete :exec
UPDATE legacy_sync_jobs
SET status = 'completed', locked_by = NULL, locked_until = NULL, updated_at = now()
WHERE id = $1 AND status = 'running' AND locked_by = $2
`

type LegacyJobCompleteParams struct {
	ID       pgtype.UUID `json:"id"`
	WorkerID pgtype.Text `json:"worker_id"`
}

func (q *Queries) LegacyJobComplete(ctx context.Context, arg LegacyJobCompleteParams) error {
	_, err := q.db.Exec(ctx, legacyJobComplete, arg.ID, arg.WorkerID)
	return err
}

const legacyJobCounts = `-- name: LegacyJobCounts :one
SELECT
    count(*) FILTER (WHERE status = 'queued')::int AS queued,
    count(*) FILTER (WHERE status = 'running')::int AS running,
    count(*) FILTER (WHERE status = 'completed')::int AS completed,
    count(*) FILTER (WHERE status = 'dead')::int AS dead
FROM legacy_sync_jobs
`

type LegacyJobCountsRow struct {
	Queued    int32 `json:"queued"`
	Running   int32 `json:"running"`
	Completed int32 `json:"completed"`
	Dead      int32 `json:"dead"`
}

func (q *Queries) LegacyJobCounts(ctx context.Context) (LegacyJobCountsRow, error) {
	row := q.db.QueryRow(ctx, legacyJobCounts)
	var i LegacyJobCountsRow
	err := row.Scan(
		&i.Queued,
		&i.Running,
		&i.Completed,
		&i.Dead,
	)
	return i, err
}

const legacyJobEnqueue = `-- name: LegacyJobEnqueue :one
INSERT INTO legacy_sync_jobs
    (job_type, entity_type, external_id, payload, unique_key, priority, deadline_at, max_attempts, run_after)
VALUES ($1, $2, $3, $4::text::jsonb,
        $5, $6, $7, $8, $9)
ON CONFLICT (unique_key) WHERE unique_key IS NOT NULL AND status IN ('queued','running')
DO UPDATE SET
    priority = LEAST(legacy_sync_jobs.priority, EXCLUDED.priority),
    run_after = LEAST(legacy_sync_jobs.run_after, EXCLUDED.run_after),
    updated_at = now()
RETURNING id, job_type, entity_type, external_id, payload, unique_key, priority, status, deadline_at, attempt, max_attempts, locked_by, locked_until, heartbeat_at, run_after, last_error, created_at, updated_at
`

type LegacyJobEnqueueParams struct {
	JobType     string             `json:"job_type"`
	EntityType  pgtype.Text        `json:"entity_type"`
	ExternalID  pgtype.Text        `json:"external_id"`
	Payload     string             `json:"payload"`
	UniqueKey   pgtype.Text        `json:"unique_key"`
	Priority    int32              `json:"priority"`
	DeadlineAt  pgtype.Timestamptz `json:"deadline_at"`
	MaxAttempts int32              `json:"max_attempts"`
	RunAfter    pgtype.Timestamptz `json:"run_after"`
}

func (q *Queries) LegacyJobEnqueue(ctx context.Context, arg LegacyJobEnqueueParams) (LegacySyncJob, error) {
	row := q.db.QueryRow(ctx, legacyJobEnqueue,
		arg.JobType,
		arg.EntityType,
		arg.ExternalID,
		arg.Payload,
		arg.UniqueKey,
		arg.Priority,
		arg.DeadlineAt,
		arg.MaxAttempts,
		arg.RunAfter,
	)
	var i LegacySyncJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.EntityType,
		&i.ExternalID,
		&i.Payload,
		&i.UniqueKey,
		&i.Priority,
		&i.Status,
		&i.DeadlineAt,
		&i.Attempt,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.HeartbeatAt,
		&i.RunAfter,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const legacyJobHeartbeat = `-- name: LegacyJobHeartbeat :exec
UPDATE legacy_sync_jobs
SET locked_until = now() + ($1 * interval '1 second'),
    heartbeat_at = now(),
    updated_at = now()
WHERE id = $2 AND status = 'running' AND locked_by = $3
`

type LegacyJobHeartbeatParams struct {
	LeaseSeconds interface{} `json:"lease_seconds"`
	ID           pgtype.UUID `json:"id"`
	WorkerID     pgtype.Text `json:"worker_id"`
}

func (q *Queries) LegacyJobHeartbeat(ctx context.Context, arg LegacyJobHeartbeatParams) error {
	_, err := q.db.Exec(ctx, legacyJobHeartbeat, arg.LeaseSeconds, arg.ID, arg.WorkerID)
	return err
}

const legacyJobListPaginated = `-- name: LegacyJobListPaginated :many
SELECT id, job_type, entity_type, external_id, payload, unique_key, priority, status, deadline_at, attempt, max_attempts, locked_by, locked_until, heartbeat_at, run_after, last_error, created_at, updated_at FROM legacy_sync_jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type LegacyJobListPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) LegacyJobListPaginated(ctx context.Context, arg LegacyJobListPaginatedParams) ([]LegacySyncJob, error) {
	rows, err := q.db.Query(ctx, legacyJobListPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegacySyncJob
	for rows.Next() {
		var i LegacySyncJob
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.EntityType,
			&i.ExternalID,
			&i.Payload,
			&i.UniqueKey,
			&i.Priority,
			&i.Status,
			&i.DeadlineAt,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockedUntil,
			&i.HeartbeatAt,
			&i.RunAfter,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const legacyJobListRecent = `-- name: LegacyJobListRecent :many
SELECT id, job_type, entity_type, external_id, payload, unique_key, priority, status, deadline_at, attempt, max_attempts, locked_by, locked_until, heartbeat_at, run_after, last_error, created_at, updated_at FROM legacy_sync_jobs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) LegacyJobListRecent(ctx context.Context, limit int32) ([]LegacySyncJob, error) {
	rows, err := q.db.Query(ctx, legacyJobListRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegacySyncJob
	for rows.Next() {
		var i LegacySyncJob
		if err := rows.Scan(
			&i.ID,
			&i.JobType,
			&i.EntityType,
			&i.ExternalID,
			&i.Payload,
			&i.UniqueKey,
			&i.Priority,
			&i.Status,
			&i.DeadlineAt,
			&i.Attempt,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockedUntil,
			&i.HeartbeatAt,
			&i.RunAfter,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const legacySyncControlGet = `-- name: LegacySyncControlGet :one
SELECT id, detection_enabled, fetch_enabled, apply_enabled, tombstone_enabled, realtime_enabled, shadow_mode, updated_at, student_enabled FROM legacy_sync_controls
WHERE id = true
`

func (q *Queries) LegacySyncControlGet(ctx context.Context) (LegacySyncControl, error) {
	row := q.db.QueryRow(ctx, legacySyncControlGet)
	var i LegacySyncControl
	err := row.Scan(
		&i.ID,
		&i.DetectionEnabled,
		&i.FetchEnabled,
		&i.ApplyEnabled,
		&i.TombstoneEnabled,
		&i.RealtimeEnabled,
		&i.ShadowMode,
		&i.UpdatedAt,
		&i.StudentEnabled,
	)
	return i, err
}

const legacySyncControlSet = `-- name: LegacySyncControlSet :one
UPDATE legacy_sync_controls
SET detection_enabled = COALESCE($1, detection_enabled),
    fetch_enabled = COALESCE($2, fetch_enabled),
    apply_enabled = COALESCE($3, apply_enabled),
    student_enabled = COALESCE($4, student_enabled),
    tombstone_enabled = COALESCE($5, tombstone_enabled),
    realtime_enabled = COALESCE($6, realtime_enabled),
    shadow_mode = COALESCE($7, shadow_mode),
    updated_at = now()
WHERE id = true
RETURNING id, detection_enabled, fetch_enabled, apply_enabled, tombstone_enabled, realtime_enabled, shadow_mode, updated_at, student_enabled
`

type LegacySyncControlSetParams struct {
	DetectionEnabled pgtype.Bool `json:"detection_enabled"`
	FetchEnabled     pgtype.Bool `json:"fetch_enabled"`
	ApplyEnabled     pgtype.Bool `json:"apply_enabled"`
	StudentEnabled   pgtype.Bool `json:"student_enabled"`
	TombstoneEnabled pgtype.Bool `json:"tombstone_enabled"`
	RealtimeEnabled  pgtype.Bool `json:"realtime_enabled"`
	ShadowMode       pgtype.Bool `json:"shadow_mode"`
}

func (q *Queries) LegacySyncControlSet(ctx context.Context, arg LegacySyncControlSetParams) (LegacySyncControl, error) {
	row := q.db.QueryRow(ctx, legacySyncControlSet,
		arg.DetectionEnabled,
		arg.FetchEnabled,
		arg.ApplyEnabled,
		arg.StudentEnabled,
		arg.TombstoneEnabled,
		arg.RealtimeEnabled,
		arg.ShadowMode,
	)
	var i LegacySyncControl
	err := row.Scan(
		&i.ID,
		&i.DetectionEnabled,
		&i.FetchEnabled,
		&i.ApplyEnabled,
		&i.TombstoneEnabled,
		&i.RealtimeEnabled,
		&i.ShadowMode,
		&i.UpdatedAt,
		&i.StudentEnabled,
	)
	return i, err
}

const outboxInsert = `-- name: OutboxInsert :one
INSERT INTO legacy_sync_outbox (source_event_key, event_type, channel, entity_type, external_id, payload)
VALUES ($1, $2, $3, $4, $5, $6::text::jsonb)
ON CONFLICT (source_event_key)
DO UPDATE SET
    event_type  = EXCLUDED.event_type,
    channel     = EXCLUDED.channel,
    entity_type = EXCLUDED.entity_type,
    external_id = EXCLUDED.external_id,
    payload     = EXCLUDED.payload,
    status      = 'pending',
    published_at = NULL,
    last_error   = NULL,
    claimed_at   = NULL,
    claim_until  = NULL
RETURNING id, source_event_key, event_type, channel, entity_type, external_id, payload, status, published_at, last_error, created_at, claimed_at, claim_until
`

type OutboxInsertParams struct {
	SourceEventKey string      `json:"source_event_key"`
	EventType      string      `json:"event_type"`
	Channel        string      `json:"channel"`
	EntityType     pgtype.Text `json:"entity_type"`
	ExternalID     pgtype.Text `json:"external_id"`
	Payload        string      `json:"payload"`
}

func (q *Queries) OutboxInsert(ctx context.Context, arg OutboxInsertParams) (LegacySyncOutbox, error) {
	row := q.db.QueryRow(ctx, outboxInsert,
		arg.SourceEventKey,
		arg.EventType,
		arg.Channel,
		arg.EntityType,
		arg.ExternalID,
		arg.Payload,
	)
	var i LegacySyncOutbox
	err := row.Scan(
		&i.ID,
		&i.SourceEventKey,
		&i.EventType,
		&i.Channel,
		&i.EntityType,
		&i.ExternalID,
		&i.Payload,
		&i.Status,
		&i.PublishedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.ClaimUntil,
	)
	return i, err
}

const snapshotGet = `-- name: SnapshotGet :one
SELECT source, entity_type, external_id, canonical_data, source_hash, parser_version, observed_at, applied_at, quality FROM legacy_entity_snapshots
WHERE source = $1 AND entity_type = $2 AND external_id = $3
`

type SnapshotGetParams struct {
	Source     string `json:"source"`
	EntityType string `json:"entity_type"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) SnapshotGet(ctx context.Context, arg SnapshotGetParams) (LegacyEntitySnapshot, error) {
	row := q.db.QueryRow(ctx, snapshotGet, arg.Source, arg.EntityType, arg.ExternalID)
	var i LegacyEntitySnapshot
	err := row.Scan(
		&i.Source,
		&i.EntityType,
		&i.ExternalID,
		&i.CanonicalData,
		&i.SourceHash,
		&i.ParserVersion,
		&i.ObservedAt,
		&i.AppliedAt,
		&i.Quality,
	)
	return i, err
}

const snapshotUpsert = `-- name: SnapshotUpsert :one
INSERT INTO legacy_entity_snapshots
    (source, entity_type, external_id, canonical_data, source_hash, parser_version, observed_at, applied_at, quality)
VALUES ($1, $2, $3, $4::text::jsonb, $5, $6, $7, $8, $9)
ON CONFLICT (source, entity_type, external_id)
DO UPDATE SET
    canonical_data = EXCLUDED.canonical_data,
    source_hash    = EXCLUDED.source_hash,
    parser_version = EXCLUDED.parser_version,
    observed_at    = EXCLUDED.observed_at,
    applied_at     = EXCLUDED.applied_at,
    quality        = EXCLUDED.quality
RETURNING source, entity_type, external_id, canonical_data, source_hash, parser_version, observed_at, applied_at, quality
`

type SnapshotUpsertParams struct {
	Source        string             `json:"source"`
	EntityType    string             `json:"entity_type"`
	ExternalID    string             `json:"external_id"`
	CanonicalData string             `json:"canonical_data"`
	SourceHash    string             `json:"source_hash"`
	ParserVersion int32              `json:"parser_version"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	Quality       string             `json:"quality"`
}

func (q *Queries) SnapshotUpsert(ctx context.Context, arg SnapshotUpsertParams) (LegacyEntitySnapshot, error) {
	row := q.db.QueryRow(ctx, snapshotUpsert,
		arg.Source,
		arg.EntityType,
		arg.ExternalID,
		arg.CanonicalData,
		arg.SourceHash,
		arg.ParserVersion,
		arg.ObservedAt,
		arg.AppliedAt,
		arg.Quality,
	)
	var i LegacyEntitySnapshot
	err := row.Scan(
		&i.Source,
		&i.EntityType,
		&i.ExternalID,
		&i.CanonicalData,
		&i.SourceHash,
		&i.ParserVersion,
		&i.ObservedAt,
		&i.AppliedAt,
		&i.Quality,
	)
	return i, err
}

const syncRunComplete = `-- name: SyncRunComplete :exec
UPDATE legacy_sync_runs
SET status = $2,
    completed_at = now(),
    pages_requested = $3,
    entities_parsed = $4,
    entities_changed = $5,
    entities_applied = $6,
    parse_failures = $7,
    reconciliation_mismatches = $8,
    source_latency_ms = $9,
    last_error = $10
WHERE id = $1
`

type SyncRunCompleteParams struct {
	ID                       pgtype.UUID `json:"id"`
	Status                   string      `json:"status"`
	PagesRequested           int32       `json:"pages_requested"`
	EntitiesParsed           int32       `json:"entities_parsed"`
	EntitiesChanged          int32       `json:"entities_changed"`
	EntitiesApplied          int32       `json:"entities_applied"`
	ParseFailures            int32       `json:"parse_failures"`
	ReconciliationMismatches int32       `json:"reconciliation_mismatches"`
	SourceLatencyMs          pgtype.Int4 `json:"source_latency_ms"`
	LastError                pgtype.Text `json:"last_error"`
}

func (q *Queries) SyncRunComplete(ctx context.Context, arg SyncRunCompleteParams) error {
	_, err := q.db.Exec(ctx, syncRunComplete,
		arg.ID,
		arg.Status,
		arg.PagesRequested,
		arg.EntitiesParsed,
		arg.EntitiesChanged,
		arg.EntitiesApplied,
		arg.ParseFailures,
		arg.ReconciliationMismatches,
		arg.SourceLatencyMs,
		arg.LastError,
	)
	return err
}

const syncRunCreate = `-- name: SyncRunCreate :one
INSERT INTO legacy_sync_runs (mode)
VALUES ($1)
RETURNING id, mode, status, started_at, completed_at, pages_requested, entities_parsed, entities_changed, entities_applied, parse_failures, reconciliation_mismatches, source_latency_ms, last_error
`

func (q *Queries) SyncRunCreate(ctx context.Context, mode string) (LegacySyncRun, error) {
	row := q.db.QueryRow(ctx, syncRunCreate, mode)
	var i LegacySyncRun
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PagesRequested,
		&i.EntitiesParsed,
		&i.EntitiesChanged,
		&i.EntitiesApplied,
		&i.ParseFailures,
		&i.ReconciliationMismatches,
		&i.SourceLatencyMs,
		&i.LastError,
	)
	return i, err
}

const syncRunGetLatest = `-- name: SyncRunGetLatest :one
SELECT id, mode, status, started_at, completed_at, pages_requested, entities_parsed, entities_changed, entities_applied, parse_failures, reconciliation_mismatches, source_latency_ms, last_error FROM legacy_sync_runs
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) SyncRunGetLatest(ctx context.Context) (LegacySyncRun, error) {
	row := q.db.QueryRow(ctx, syncRunGetLatest)
	var i LegacySyncRun
	err := row.Scan(
		&i.ID,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.PagesRequested,
		&i.EntitiesParsed,
		&i.EntitiesChanged,
		&i.EntitiesApplied,
		&i.ParseFailures,
		&i.ReconciliationMismatches,
		&i.SourceLatencyMs,
		&i.LastError,
	)
	return i, err
}

const syncRunListRecent = `-- name: SyncRunListRecent :many
SELECT id, mode, status, started_at, completed_at, pages_requested, entities_parsed, entities_changed, entities_applied, parse_failures, reconciliation_mismatches, source_latency_ms, last_error FROM legacy_sync_runs
ORDER BY started_at DESC
LIMIT $1
`

func (q *Queries) SyncRunListRecent(ctx context.Context, limit int32) ([]LegacySyncRun, error) {
	rows, err := q.db.Query(ctx, syncRunListRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LegacySyncRun
	for rows.Next() {
		var i LegacySyncRun
		if err := rows.Scan(
			&i.ID,
			&i.Mode,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PagesRequested,
			&i.EntitiesParsed,
			&i.EntitiesChanged,
			&i.EntitiesApplied,
			&i.ParseFailures,
			&i.ReconciliationMismatches,
			&i.SourceLatencyMs,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
