// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CrmJobStatus string

const (
	CrmJobStatusQueued    CrmJobStatus = "queued"
	CrmJobStatusRunning   CrmJobStatus = "running"
	CrmJobStatusRetry     CrmJobStatus = "retry"
	CrmJobStatusSucceeded CrmJobStatus = "succeeded"
	CrmJobStatusFailed    CrmJobStatus = "failed"
)

func (e *CrmJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrmJobStatus(s)
	case string:
		*e = CrmJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CrmJobStatus: %T", src)
	}
	return nil
}

type NullCrmJobStatus struct {
	CrmJobStatus CrmJobStatus `json:"crm_job_status"`
	Valid        bool         `json:"valid"` // Valid is true if CrmJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrmJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CrmJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrmJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrmJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrmJobStatus), nil
}

type CrmJobType string

const (
	CrmJobTypeImportSnapshot       CrmJobType = "import_snapshot"
	CrmJobTypeStudentSync          CrmJobType = "student_sync"
	CrmJobTypeCourseReconcileApply CrmJobType = "course_reconcile_apply"
	CrmJobTypeCourseReconcileDiff  CrmJobType = "course_reconcile_diff"
)

func (e *CrmJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrmJobType(s)
	case string:
		*e = CrmJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for CrmJobType: %T", src)
	}
	return nil
}

type NullCrmJobType struct {
	CrmJobType CrmJobType `json:"crm_job_type"`
	Valid      bool       `json:"valid"` // Valid is true if CrmJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrmJobType) Scan(value interface{}) error {
	if value == nil {
		ns.CrmJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrmJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrmJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrmJobType), nil
}

type DiffAction string

const (
	DiffActionAdd    DiffAction = "add"
	DiffActionRemove DiffAction = "remove"
)

func (e *DiffAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiffAction(s)
	case string:
		*e = DiffAction(s)
	default:
		return fmt.Errorf("unsupported scan type for DiffAction: %T", src)
	}
	return nil
}

type NullDiffAction struct {
	DiffAction DiffAction `json:"diff_action"`
	Valid      bool       `json:"valid"` // Valid is true if DiffAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiffAction) Scan(value interface{}) error {
	if value == nil {
		ns.DiffAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiffAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiffAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiffAction), nil
}

type OverrideAction string

const (
	OverrideActionInclude OverrideAction = "include"
	OverrideActionExclude OverrideAction = "exclude"
)

func (e *OverrideAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OverrideAction(s)
	case string:
		*e = OverrideAction(s)
	default:
		return fmt.Errorf("unsupported scan type for OverrideAction: %T", src)
	}
	return nil
}

type NullOverrideAction struct {
	OverrideAction OverrideAction `json:"override_action"`
	Valid          bool           `json:"valid"` // Valid is true if OverrideAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOverrideAction) Scan(value interface{}) error {
	if value == nil {
		ns.OverrideAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OverrideAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOverrideAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OverrideAction), nil
}

type AbsenceAuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	AbsenceID pgtype.UUID        `json:"absence_id"`
	Action    string             `json:"action"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ActorRole string             `json:"actor_role"`
	Details   []byte             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AbsenceMissedSession struct {
	ID        pgtype.UUID        `json:"id"`
	AbsenceID pgtype.UUID        `json:"absence_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AbsenceSitIn struct {
	ID        pgtype.UUID        `json:"id"`
	AbsenceID pgtype.UUID        `json:"absence_id"`
	SessionID pgtype.UUID        `json:"session_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AppSetting struct {
	ID              bool               `json:"id"`
	InstituteTz     string             `json:"institute_tz"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	AbsencePolicies []byte             `json:"absence_policies"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	Payload     []byte             `json:"payload"`
}

type AuthSession struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	PasswordVersion int32              `json:"password_version"`
}

type Course struct {
	ID                         pgtype.UUID        `json:"id"`
	Code                       string             `json:"code"`
	Name                       string             `json:"name"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CourseNo                   int64              `json:"course_no"`
	Year                       pgtype.Int2        `json:"year"`
	TeacherID                  pgtype.UUID        `json:"teacher_id"`
	SubjectID                  pgtype.UUID        `json:"subject_id"`
	Hour                       pgtype.Int4        `json:"hour"`
	StudentCount               pgtype.Int4        `json:"student_count"`
	CourseType                 pgtype.Text        `json:"course_type"`
	CrmFilterEnabled           bool               `json:"crm_filter_enabled"`
	CrmFilter                  []byte             `json:"crm_filter"`
	CrmFilterUpdatedAt         pgtype.Timestamptz `json:"crm_filter_updated_at"`
	CrmRosterLocked            bool               `json:"crm_roster_locked"`
	CrmFilterVersion           int32              `json:"crm_filter_version"`
	CrmLastAppliedSnapshotID   pgtype.UUID        `json:"crm_last_applied_snapshot_id"`
	CrmPendingReviewSnapshotID pgtype.UUID        `json:"crm_pending_review_snapshot_id"`
	CrmPinnedSnapshotID        pgtype.UUID        `json:"crm_pinned_snapshot_id"`
	CrmPendingReviewSummary    []byte             `json:"crm_pending_review_summary"`
	CycleID                    pgtype.Text        `json:"cycle_id"`
	Level                      pgtype.Int2        `json:"level"`
	RootCourseGroupID          pgtype.UUID        `json:"root_course_group_id"`
}

type CourseRosterOverride struct {
	ID              pgtype.UUID        `json:"id"`
	CourseID        pgtype.UUID        `json:"course_id"`
	StudentID       pgtype.UUID        `json:"student_id"`
	Action          OverrideAction     `json:"action"`
	CreatedByUserID pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedByUserID pgtype.UUID        `json:"updated_by_user_id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type CourseStudent struct {
	CourseID  pgtype.UUID        `json:"course_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// enrolled: confirmed, paid student (default). draft: tentative prospect, blocks busy ranges.
	Status string `json:"status"`
}

type CrmCycle struct {
	ID             string             `json:"id"`
	Label          string             `json:"label"`
	LastImportedAt pgtype.Timestamptz `json:"last_imported_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CrmJob struct {
	ID          pgtype.UUID        `json:"id"`
	JobType     CrmJobType         `json:"job_type"`
	Status      CrmJobStatus       `json:"status"`
	Payload     []byte             `json:"payload"`
	UniqueKey   pgtype.Text        `json:"unique_key"`
	Result      []byte             `json:"result"`
	LockedBy    pgtype.Text        `json:"locked_by"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	HeartbeatAt pgtype.Timestamptz `json:"heartbeat_at"`
	Attempt     int32              `json:"attempt"`
	MaxAttempts int32              `json:"max_attempts"`
	RunAfter    pgtype.Timestamptz `json:"run_after"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CrmPendingDiff struct {
	CourseID   pgtype.UUID `json:"course_id"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	DiffAction DiffAction  `json:"diff_action"`
	Seq        int32       `json:"seq"`
	StudentID  pgtype.UUID `json:"student_id"`
	Wcode      string      `json:"wcode"`
	FullName   string      `json:"full_name"`
}

type CrmRow struct {
	RowHash             string             `json:"row_hash"`
	CycleLabel          string             `json:"cycle_label"`
	CourseName          string             `json:"course_name"`
	Wcode               string             `json:"wcode"`
	FirstName           pgtype.Text        `json:"first_name"`
	LastName            pgtype.Text        `json:"last_name"`
	Nickname            pgtype.Text        `json:"nickname"`
	SecondarySchool     pgtype.Text        `json:"secondary_school"`
	AcademicLevel       pgtype.Text        `json:"academic_level"`
	MobilePhone         pgtype.Text        `json:"mobile_phone"`
	Hours               pgtype.Int4        `json:"hours"`
	TeachersRaw         pgtype.Text        `json:"teachers_raw"`
	PrimaryEmail        pgtype.Text        `json:"primary_email"`
	ParentName          pgtype.Text        `json:"parent_name"`
	ParentPhone         pgtype.Text        `json:"parent_phone"`
	ParentEmail         pgtype.Text        `json:"parent_email"`
	OrderQuoteUpdatedAt pgtype.Timestamptz `json:"order_quote_updated_at"`
	ImportedAt          pgtype.Timestamptz `json:"imported_at"`
	SnapshotID          pgtype.UUID        `json:"snapshot_id"`
	XlsxRowNumber       int32              `json:"xlsx_row_number"`
}

type CrmSnapshot struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    string             `json:"status"`
	RowCount  int32              `json:"row_count"`
	ErrorMsg  pgtype.Text        `json:"error_msg"`
}

type CrmState struct {
	Singleton        bool               `json:"singleton"`
	ActiveSnapshotID pgtype.UUID        `json:"active_snapshot_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CrmUploadBlob struct {
	ID        string             `json:"id"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type HttpRateLimitEvent struct {
	Key       string             `json:"key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	ID             int64              `json:"id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	StatusCode     pgtype.Int4        `json:"status_code"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type Room struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Capacity  pgtype.Int4        `json:"capacity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RoomAvailability struct {
	ID        pgtype.UUID                      `json:"id"`
	RoomID    pgtype.UUID                      `json:"room_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt pgtype.Timestamptz               `json:"updated_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
}

type RootCourseGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SitInRuleID pgtype.UUID        `json:"sit_in_rule_id"`
}

type Session struct {
	ID        pgtype.UUID                      `json:"id"`
	SeriesID  pgtype.UUID                      `json:"series_id"`
	CourseID  pgtype.UUID                      `json:"course_id"`
	RoomID    pgtype.UUID                      `json:"room_id"`
	TeacherID pgtype.UUID                      `json:"teacher_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt pgtype.Timestamptz               `json:"updated_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
	Version   int32                            `json:"version"`
}

type SessionAttendance struct {
	SessionID pgtype.UUID        `json:"session_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SessionSeries struct {
	ID              pgtype.UUID        `json:"id"`
	CourseID        pgtype.UUID        `json:"course_id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	TeacherID       pgtype.UUID        `json:"teacher_id"`
	InstituteTz     string             `json:"institute_tz"`
	StartLocalTime  pgtype.Time        `json:"start_local_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Count           pgtype.Int4        `json:"count"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Weekdays        []int16            `json:"weekdays"`
	Version         int32              `json:"version"`
}

type SitInRule struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Predicate   []byte             `json:"predicate"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SmsCircuitBreakerState struct {
	Provider        string             `json:"provider"`
	FailureCount    int32              `json:"failure_count"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	OpenUntil       pgtype.Timestamptz `json:"open_until"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	ID           pgtype.UUID        `json:"id"`
	Wcode        string             `json:"wcode"`
	FullName     string             `json:"full_name"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ParentPhone  pgtype.Text        `json:"parent_phone"`
	StudentPhone pgtype.Text        `json:"student_phone"`
}

type StudentAbsence struct {
	ID                  pgtype.UUID        `json:"id"`
	Wcode               string             `json:"wcode"`
	CourseID            pgtype.UUID        `json:"course_id"`
	DateFrom            pgtype.Date        `json:"date_from"`
	DateTo              pgtype.Date        `json:"date_to"`
	Reason              pgtype.Text        `json:"reason"`
	SitInCourseID       pgtype.UUID        `json:"sit_in_course_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	SitInMethod         pgtype.Text        `json:"sit_in_method"`
	SubjectID           pgtype.UUID        `json:"subject_id"`
	Status              string             `json:"status"`
	ReasonCategory      pgtype.Text        `json:"reason_category"`
	AdminNotes          pgtype.Text        `json:"admin_notes"`
	StudentName         pgtype.Text        `json:"student_name"`
	StudentEmail        pgtype.Text        `json:"student_email"`
	StudentPhone        pgtype.Text        `json:"student_phone"`
	ReviewedBy          pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	SitInOverridden     bool               `json:"sit_in_overridden"`
	SitInOverriddenBy   pgtype.UUID        `json:"sit_in_overridden_by"`
	SitInOverrideReason pgtype.Text        `json:"sit_in_override_reason"`
	Version             int32              `json:"version"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type StudentBusyRange struct {
	ID        pgtype.UUID                      `json:"id"`
	StudentID pgtype.UUID                      `json:"student_id"`
	SessionID pgtype.UUID                      `json:"session_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
}

type StudentOtpLockout struct {
	Wcode        string             `json:"wcode"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
	FailureCount int32              `json:"failure_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type StudentParentVerificationSession struct {
	ID                pgtype.UUID        `json:"id"`
	Wcode             string             `json:"wcode"`
	ParentPhone       string             `json:"parent_phone"`
	Status            string             `json:"status"`
	OtpCodeHash       pgtype.Text        `json:"otp_code_hash"`
	OtpAttemptCount   int32              `json:"otp_attempt_count"`
	OtpLockedUntil    pgtype.Timestamptz `json:"otp_locked_until"`
	OtpLastSentAt     pgtype.Timestamptz `json:"otp_last_sent_at"`
	OtpCodeExpiresAt  pgtype.Timestamptz `json:"otp_code_expires_at"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAbsenceID pgtype.UUID        `json:"consumed_absence_id"`
	Version           int32              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Subject struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SubjectActiveCourse struct {
	SubjectID pgtype.UUID        `json:"subject_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeacherAvailability struct {
	ID        pgtype.UUID                      `json:"id"`
	TeacherID pgtype.UUID                      `json:"teacher_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt pgtype.Timestamptz               `json:"updated_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Username        string             `json:"username"`
	Role            string             `json:"role"`
	PasswordHash    string             `json:"password_hash"`
	PasswordVersion int32              `json:"password_version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
