// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CrmJobStatus string

const (
	CrmJobStatusQueued    CrmJobStatus = "queued"
	CrmJobStatusRunning   CrmJobStatus = "running"
	CrmJobStatusRetry     CrmJobStatus = "retry"
	CrmJobStatusSucceeded CrmJobStatus = "succeeded"
	CrmJobStatusFailed    CrmJobStatus = "failed"
)

func (e *CrmJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrmJobStatus(s)
	case string:
		*e = CrmJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CrmJobStatus: %T", src)
	}
	return nil
}

type NullCrmJobStatus struct {
	CrmJobStatus CrmJobStatus `json:"crm_job_status"`
	Valid        bool         `json:"valid"` // Valid is true if CrmJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrmJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CrmJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrmJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrmJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrmJobStatus), nil
}

type CrmJobType string

const (
	CrmJobTypeImportSnapshot       CrmJobType = "import_snapshot"
	CrmJobTypeStudentSync          CrmJobType = "student_sync"
	CrmJobTypeCourseReconcileApply CrmJobType = "course_reconcile_apply"
	CrmJobTypeCourseReconcileDiff  CrmJobType = "course_reconcile_diff"
	CrmJobTypeCrossStudyProcess    CrmJobType = "cross_study_process"
)

func (e *CrmJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CrmJobType(s)
	case string:
		*e = CrmJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for CrmJobType: %T", src)
	}
	return nil
}

type NullCrmJobType struct {
	CrmJobType CrmJobType `json:"crm_job_type"`
	Valid      bool       `json:"valid"` // Valid is true if CrmJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCrmJobType) Scan(value interface{}) error {
	if value == nil {
		ns.CrmJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CrmJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCrmJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CrmJobType), nil
}

type DiffAction string

const (
	DiffActionAdd    DiffAction = "add"
	DiffActionRemove DiffAction = "remove"
)

func (e *DiffAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiffAction(s)
	case string:
		*e = DiffAction(s)
	default:
		return fmt.Errorf("unsupported scan type for DiffAction: %T", src)
	}
	return nil
}

type NullDiffAction struct {
	DiffAction DiffAction `json:"diff_action"`
	Valid      bool       `json:"valid"` // Valid is true if DiffAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiffAction) Scan(value interface{}) error {
	if value == nil {
		ns.DiffAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiffAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiffAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiffAction), nil
}

type OverrideAction string

const (
	OverrideActionInclude OverrideAction = "include"
	OverrideActionExclude OverrideAction = "exclude"
)

func (e *OverrideAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OverrideAction(s)
	case string:
		*e = OverrideAction(s)
	default:
		return fmt.Errorf("unsupported scan type for OverrideAction: %T", src)
	}
	return nil
}

type NullOverrideAction struct {
	OverrideAction OverrideAction `json:"override_action"`
	Valid          bool           `json:"valid"` // Valid is true if OverrideAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOverrideAction) Scan(value interface{}) error {
	if value == nil {
		ns.OverrideAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OverrideAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOverrideAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OverrideAction), nil
}

type AbsenceAuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	AbsenceID pgtype.UUID        `json:"absence_id"`
	Action    string             `json:"action"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ActorRole string             `json:"actor_role"`
	Details   []byte             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AbsenceMissedSession struct {
	ID                          pgtype.UUID        `json:"id"`
	AbsenceID                   pgtype.UUID        `json:"absence_id"`
	SessionID                   pgtype.UUID        `json:"session_id"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	SessionVersionAtSubmission  pgtype.Int4        `json:"session_version_at_submission"`
	OriginalStartAt             pgtype.Timestamptz `json:"original_start_at"`
	OriginalEndAt               pgtype.Timestamptz `json:"original_end_at"`
	SessionSnapshotAtSubmission []byte             `json:"session_snapshot_at_submission"`
	SnapshotSchemaVersion       pgtype.Int2        `json:"snapshot_schema_version"`
	SnapshotCapturedAt          pgtype.Timestamptz `json:"snapshot_captured_at"`
	SnapshotQuality             string             `json:"snapshot_quality"`
	SnapshotSource              pgtype.Text        `json:"snapshot_source"`
}

type AbsenceScheduleIssue struct {
	ID                            pgtype.UUID        `json:"id"`
	AbsenceID                     pgtype.UUID        `json:"absence_id"`
	IssueType                     string             `json:"issue_type"`
	Severity                      string             `json:"severity"`
	Status                        string             `json:"status"`
	SourceSessionID               pgtype.UUID        `json:"source_session_id"`
	SitInSessionID                pgtype.UUID        `json:"sit_in_session_id"`
	MissedSessionID               pgtype.UUID        `json:"missed_session_id"`
	FirstSessionChangeID          pgtype.UUID        `json:"first_session_change_id"`
	LatestSessionChangeID         pgtype.UUID        `json:"latest_session_change_id"`
	DetailsJson                   []byte             `json:"details_json"`
	SuggestedResolutionJson       []byte             `json:"suggested_resolution_json"`
	DetectedAt                    pgtype.Timestamptz `json:"detected_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt                    pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy                    pgtype.UUID        `json:"resolved_by"`
	ResolutionAction              pgtype.Text        `json:"resolution_action"`
	Fingerprint                   string             `json:"fingerprint"`
	IssueVersion                  int32              `json:"issue_version"`
	AssignedTo                    pgtype.UUID        `json:"assigned_to"`
	ReviewReason                  pgtype.Text        `json:"review_reason"`
	ReviewDueAt                   pgtype.Timestamptz `json:"review_due_at"`
	ReviewNote                    pgtype.Text        `json:"review_note"`
	AssignmentSnapshotAtDetection []byte             `json:"assignment_snapshot_at_detection"`
	AssignmentSnapshotQuality     string             `json:"assignment_snapshot_quality"`
	AssignmentSnapshotSource      pgtype.Text        `json:"assignment_snapshot_source"`
}

type AbsenceSitIn struct {
	ID                          pgtype.UUID        `json:"id"`
	AbsenceID                   pgtype.UUID        `json:"absence_id"`
	SessionID                   pgtype.UUID        `json:"session_id"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	SessionVersionAtAssignment  pgtype.Int4        `json:"session_version_at_assignment"`
	AssignedAt                  pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy                  pgtype.UUID        `json:"assigned_by"`
	AssignmentSource            string             `json:"assignment_source"`
	SessionSnapshotAtAssignment []byte             `json:"session_snapshot_at_assignment"`
	SnapshotSchemaVersion       pgtype.Int2        `json:"snapshot_schema_version"`
	SnapshotCapturedAt          pgtype.Timestamptz `json:"snapshot_captured_at"`
	SnapshotQuality             string             `json:"snapshot_quality"`
	SnapshotSource              pgtype.Text        `json:"snapshot_source"`
}

type AbsenceSitInAssignmentEvent struct {
	ID                pgtype.UUID        `json:"id"`
	AbsenceID         pgtype.UUID        `json:"absence_id"`
	PreviousSessionID pgtype.UUID        `json:"previous_session_id"`
	NewSessionID      pgtype.UUID        `json:"new_session_id"`
	Action            string             `json:"action"`
	Reason            string             `json:"reason"`
	SessionChangeID   pgtype.UUID        `json:"session_change_id"`
	ActorID           pgtype.UUID        `json:"actor_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AppSetting struct {
	ID                             bool               `json:"id"`
	InstituteTz                    string             `json:"institute_tz"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	AbsencePolicies                []byte             `json:"absence_policies"`
	SitInEmailConfig               []byte             `json:"sit_in_email_config"`
	SitInChangeSmsEnabled          bool               `json:"sit_in_change_sms_enabled"`
	SitInChangeSmsTemplate         string             `json:"sit_in_change_sms_template"`
	SitInChangeEmailEnabled        bool               `json:"sit_in_change_email_enabled"`
	SitInChangeEmailSubject        string             `json:"sit_in_change_email_subject"`
	SitInChangeEmailBody           string             `json:"sit_in_change_email_body"`
	SitInChangeAutoNotifySafeMoves bool               `json:"sit_in_change_auto_notify_safe_moves"`
	SitInChangeWarningHours        int32              `json:"sit_in_change_warning_hours"`
	SitInChangeCriticalHours       int32              `json:"sit_in_change_critical_hours"`
	AllowMoveIntoPast              bool               `json:"allow_move_into_past"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	Payload     []byte             `json:"payload"`
}

type AuthSession struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	PasswordVersion int32              `json:"password_version"`
}

type Course struct {
	ID                         pgtype.UUID        `json:"id"`
	Code                       string             `json:"code"`
	Name                       string             `json:"name"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	CourseNo                   int64              `json:"course_no"`
	Year                       pgtype.Int2        `json:"year"`
	TeacherID                  pgtype.UUID        `json:"teacher_id"`
	SubjectID                  pgtype.UUID        `json:"subject_id"`
	Hour                       pgtype.Int4        `json:"hour"`
	StudentCount               pgtype.Int4        `json:"student_count"`
	CourseType                 pgtype.Text        `json:"course_type"`
	CrmFilterEnabled           bool               `json:"crm_filter_enabled"`
	CrmFilter                  []byte             `json:"crm_filter"`
	CrmFilterUpdatedAt         pgtype.Timestamptz `json:"crm_filter_updated_at"`
	CrmRosterLocked            bool               `json:"crm_roster_locked"`
	CrmFilterVersion           int32              `json:"crm_filter_version"`
	CrmLastAppliedSnapshotID   pgtype.UUID        `json:"crm_last_applied_snapshot_id"`
	CrmPendingReviewSnapshotID pgtype.UUID        `json:"crm_pending_review_snapshot_id"`
	CrmPinnedSnapshotID        pgtype.UUID        `json:"crm_pinned_snapshot_id"`
	CrmPendingReviewSummary    []byte             `json:"crm_pending_review_summary"`
	CycleID                    pgtype.Text        `json:"cycle_id"`
	Level                      pgtype.Int2        `json:"level"`
	RootCourseGroupID          pgtype.UUID        `json:"root_course_group_id"`
	LegacyCourseID             pgtype.Text        `json:"legacy_course_id"`
	LegacyLastSyncedAt         pgtype.Timestamptz `json:"legacy_last_synced_at"`
	CohortID                   pgtype.UUID        `json:"cohort_id"`
	Version                    int32              `json:"version"`
}

type CourseCohort struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CourseRosterOverride struct {
	ID                     pgtype.UUID        `json:"id"`
	CourseID               pgtype.UUID        `json:"course_id"`
	StudentID              pgtype.UUID        `json:"student_id"`
	Action                 OverrideAction     `json:"action"`
	CreatedByUserID        pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedByUserID        pgtype.UUID        `json:"updated_by_user_id"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	OverrideSource         pgtype.Text        `json:"override_source"`
	CrossStudyAssignmentID pgtype.UUID        `json:"cross_study_assignment_id"`
}

type CourseStudent struct {
	CourseID  pgtype.UUID        `json:"course_id"`
	StudentID pgtype.UUID        `json:"student_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// enrolled: confirmed, paid student (default). draft: tentative prospect, blocks busy ranges.
	Status string `json:"status"`
}

type CourseTeacher struct {
	CourseID  pgtype.UUID `json:"course_id"`
	TeacherID pgtype.UUID `json:"teacher_id"`
	IsPrimary bool        `json:"is_primary"`
}

type CrmCrossStudyAssignment struct {
	ID                              pgtype.UUID        `json:"id"`
	SnapshotID                      pgtype.UUID        `json:"snapshot_id"`
	Wcode                           string             `json:"wcode"`
	SourceCourseID                  pgtype.UUID        `json:"source_course_id"`
	DestCourseAID                   pgtype.UUID        `json:"dest_course_a_id"`
	DestCourseBID                   pgtype.UUID        `json:"dest_course_b_id"`
	AssignedCourseID                pgtype.UUID        `json:"assigned_course_id"`
	ExtraNoteSnapshot               string             `json:"extra_note_snapshot"`
	ExtraNoteHash                   string             `json:"extra_note_hash"`
	AssignedCourseEnrollmentCreated bool               `json:"assigned_course_enrollment_created"`
	DestCourseAEnrollmentCreated    bool               `json:"dest_course_a_enrollment_created"`
	DestCourseBEnrollmentCreated    bool               `json:"dest_course_b_enrollment_created"`
	SourceCourseEnrollmentRemoved   bool               `json:"source_course_enrollment_removed"`
	SourceValid                     bool               `json:"source_valid"`
	Status                          string             `json:"status"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	CrmCourseNameSnapshot           string             `json:"crm_course_name_snapshot"`
	CrmRowHashSnapshot              string             `json:"crm_row_hash_snapshot"`
	CrmXlsxRowNumberSnapshot        pgtype.Int4        `json:"crm_xlsx_row_number_snapshot"`
	DestCourseAWeekdays             []int16            `json:"dest_course_a_weekdays"`
	DestCourseBWeekdays             []int16            `json:"dest_course_b_weekdays"`
}

type CrmCycle struct {
	ID             string             `json:"id"`
	Label          string             `json:"label"`
	LastImportedAt pgtype.Timestamptz `json:"last_imported_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CrmJob struct {
	ID          pgtype.UUID        `json:"id"`
	JobType     CrmJobType         `json:"job_type"`
	Status      CrmJobStatus       `json:"status"`
	Payload     []byte             `json:"payload"`
	UniqueKey   pgtype.Text        `json:"unique_key"`
	Result      []byte             `json:"result"`
	LockedBy    pgtype.Text        `json:"locked_by"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	HeartbeatAt pgtype.Timestamptz `json:"heartbeat_at"`
	Attempt     int32              `json:"attempt"`
	MaxAttempts int32              `json:"max_attempts"`
	RunAfter    pgtype.Timestamptz `json:"run_after"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CrmPendingDiff struct {
	CourseID   pgtype.UUID `json:"course_id"`
	SnapshotID pgtype.UUID `json:"snapshot_id"`
	DiffAction DiffAction  `json:"diff_action"`
	Seq        int32       `json:"seq"`
	StudentID  pgtype.UUID `json:"student_id"`
	Wcode      string      `json:"wcode"`
	FullName   string      `json:"full_name"`
}

type CrmRow struct {
	RowHash             string             `json:"row_hash"`
	CycleLabel          string             `json:"cycle_label"`
	CourseName          string             `json:"course_name"`
	Wcode               string             `json:"wcode"`
	FirstName           pgtype.Text        `json:"first_name"`
	LastName            pgtype.Text        `json:"last_name"`
	Nickname            pgtype.Text        `json:"nickname"`
	SecondarySchool     pgtype.Text        `json:"secondary_school"`
	AcademicLevel       pgtype.Text        `json:"academic_level"`
	MobilePhone         pgtype.Text        `json:"mobile_phone"`
	Hours               pgtype.Int4        `json:"hours"`
	TeachersRaw         pgtype.Text        `json:"teachers_raw"`
	PrimaryEmail        pgtype.Text        `json:"primary_email"`
	ParentName          pgtype.Text        `json:"parent_name"`
	ParentPhone         pgtype.Text        `json:"parent_phone"`
	ParentEmail         pgtype.Text        `json:"parent_email"`
	OrderQuoteUpdatedAt pgtype.Timestamptz `json:"order_quote_updated_at"`
	ImportedAt          pgtype.Timestamptz `json:"imported_at"`
	SnapshotID          pgtype.UUID        `json:"snapshot_id"`
	XlsxRowNumber       int32              `json:"xlsx_row_number"`
	ExtraNote           string             `json:"extra_note"`
}

type CrmSnapshot struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    string             `json:"status"`
	RowCount  int32              `json:"row_count"`
	ErrorMsg  pgtype.Text        `json:"error_msg"`
}

type CrmState struct {
	Singleton        bool               `json:"singleton"`
	ActiveSnapshotID pgtype.UUID        `json:"active_snapshot_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CrmUploadBlob struct {
	ID        string             `json:"id"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EmailDeliveryClaim struct {
	ID             pgtype.UUID        `json:"id"`
	WorkflowID     pgtype.UUID        `json:"workflow_id"`
	LocalDate      pgtype.Date        `json:"local_date"`
	RecipientEmail string             `json:"recipient_email"`
	ClaimedAt      pgtype.Timestamptz `json:"claimed_at"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	SendingAt      pgtype.Timestamptz `json:"sending_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	FailedAt       pgtype.Timestamptz `json:"failed_at"`
	LastError      pgtype.Text        `json:"last_error"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type EmailTemplate struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Subject   string             `json:"subject"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	BuiltIn   bool               `json:"built_in"`
}

type EmailWorkflow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Enabled            bool               `json:"enabled"`
	TemplateID         pgtype.UUID        `json:"template_id"`
	TriggerDescription string             `json:"trigger_description"`
	Recipients         []string           `json:"recipients"`
	LastSentAt         pgtype.Timestamptz `json:"last_sent_at"`
	LastSentCount      int32              `json:"last_sent_count"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type HttpRateLimitEvent struct {
	Key       string             `json:"key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	ID             int64              `json:"id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	Scope          string             `json:"scope"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestHash    string             `json:"request_hash"`
	StatusCode     pgtype.Int4        `json:"status_code"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type NotificationOutbox struct {
	ID                pgtype.UUID        `json:"id"`
	AbsenceID         pgtype.UUID        `json:"absence_id"`
	AssignmentID      pgtype.UUID        `json:"assignment_id"`
	SessionVersion    int32              `json:"session_version"`
	MessageType       string             `json:"message_type"`
	Recipient         string             `json:"recipient"`
	Channel           string             `json:"channel"`
	Payload           []byte             `json:"payload"`
	Status            string             `json:"status"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	FailureReason     pgtype.Text        `json:"failure_reason"`
	AttemptCount      int32              `json:"attempt_count"`
	AvailableAt       pgtype.Timestamptz `json:"available_at"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	IdempotencyKey    string             `json:"idempotency_key"`
}

type OutboxEvent struct {
	ID               pgtype.UUID        `json:"id"`
	EventType        string             `json:"event_type"`
	AggregateID      pgtype.UUID        `json:"aggregate_id"`
	AggregateVersion int32              `json:"aggregate_version"`
	Payload          []byte             `json:"payload"`
	Status           string             `json:"status"`
	Attempts         int32              `json:"attempts"`
	AvailableAt      pgtype.Timestamptz `json:"available_at"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	LastError        pgtype.Text        `json:"last_error"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Room struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Capacity  pgtype.Int4        `json:"capacity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RoomAvailability struct {
	ID        pgtype.UUID                      `json:"id"`
	RoomID    pgtype.UUID                      `json:"room_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt pgtype.Timestamptz               `json:"updated_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
}

type RootCourseGroup struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	SitInRuleID pgtype.UUID        `json:"sit_in_rule_id"`
}

type SatVerbalPolicyMapping struct {
	ID         pgtype.UUID        `json:"id"`
	RuleID     string             `json:"rule_id"`
	CourseID   pgtype.UUID        `json:"course_id"`
	PolicyRule []byte             `json:"policy_rule"`
	PolicyHash string             `json:"policy_hash"`
	Active     bool               `json:"active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        pgtype.UUID                      `json:"id"`
	SeriesID  pgtype.UUID                      `json:"series_id"`
	CourseID  pgtype.UUID                      `json:"course_id"`
	RoomID    pgtype.UUID                      `json:"room_id"`
	TeacherID pgtype.UUID                      `json:"teacher_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt pgtype.Timestamptz               `json:"updated_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
	Version   int32                            `json:"version"`
}

type SessionAttendance struct {
	SessionID              pgtype.UUID        `json:"session_id"`
	StudentID              pgtype.UUID        `json:"student_id"`
	Status                 string             `json:"status"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	OverrideSource         pgtype.Text        `json:"override_source"`
	CrossStudyAssignmentID pgtype.UUID        `json:"cross_study_assignment_id"`
}

type SessionChange struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	SessionVersion int32              `json:"session_version"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	ChangedBy      pgtype.UUID        `json:"changed_by"`
	ChangeSource   string             `json:"change_source"`
	ChangedFields  []byte             `json:"changed_fields"`
	BeforeSnapshot []byte             `json:"before_snapshot"`
	AfterSnapshot  []byte             `json:"after_snapshot"`
	OldStartAt     pgtype.Timestamptz `json:"old_start_at"`
	OldEndAt       pgtype.Timestamptz `json:"old_end_at"`
	NewStartAt     pgtype.Timestamptz `json:"new_start_at"`
	NewEndAt       pgtype.Timestamptz `json:"new_end_at"`
	OldCourseID    pgtype.UUID        `json:"old_course_id"`
	NewCourseID    pgtype.UUID        `json:"new_course_id"`
	OldRoomID      pgtype.UUID        `json:"old_room_id"`
	NewRoomID      pgtype.UUID        `json:"new_room_id"`
	OldTeacherID   pgtype.UUID        `json:"old_teacher_id"`
	NewTeacherID   pgtype.UUID        `json:"new_teacher_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SessionChangeBatch struct {
	ID             pgtype.UUID        `json:"id"`
	RequestedCount int32              `json:"requested_count"`
	SucceededCount int32              `json:"succeeded_count"`
	FailedCount    int32              `json:"failed_count"`
	Status         string             `json:"status"`
	RequestedBy    pgtype.UUID        `json:"requested_by"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SessionChangeImpactRun struct {
	SessionChangeID   pgtype.UUID        `json:"session_change_id"`
	Status            string             `json:"status"`
	LastError         pgtype.Text        `json:"last_error"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ProcessingAttempt int32              `json:"processing_attempt"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
	AnalysisResult    []byte             `json:"analysis_result"`
	CreatedIssueIds   []pgtype.UUID      `json:"created_issue_ids"`
	ErrorCategory     pgtype.Text        `json:"error_category"`
	Retryable         bool               `json:"retryable"`
}

type SessionChangeImpactTarget struct {
	SessionChangeID pgtype.UUID `json:"session_change_id"`
	AbsenceID       pgtype.UUID `json:"absence_id"`
	RelationType    string      `json:"relation_type"`
}

type SessionSeries struct {
	ID              pgtype.UUID        `json:"id"`
	CourseID        pgtype.UUID        `json:"course_id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	TeacherID       pgtype.UUID        `json:"teacher_id"`
	InstituteTz     string             `json:"institute_tz"`
	StartLocalTime  pgtype.Time        `json:"start_local_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Count           pgtype.Int4        `json:"count"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Weekdays        []int16            `json:"weekdays"`
	Version         int32              `json:"version"`
}

type SitInPriority struct {
	ID                pgtype.UUID        `json:"id"`
	RootCourseGroupID pgtype.UUID        `json:"root_course_group_id"`
	SitInRuleID       pgtype.UUID        `json:"sit_in_rule_id"`
	PriorityLevel     int16              `json:"priority_level"`
	Label             string             `json:"label"`
	TargetRank        pgtype.Int2        `json:"target_rank"`
	TargetSection     pgtype.Int2        `json:"target_section"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type SitInRule struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Predicate   []byte             `json:"predicate"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SmsCircuitBreakerState struct {
	Provider        string             `json:"provider"`
	FailureCount    int32              `json:"failure_count"`
	WindowStartedAt pgtype.Timestamptz `json:"window_started_at"`
	OpenUntil       pgtype.Timestamptz `json:"open_until"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SmsOtpDelivery struct {
	ID               pgtype.UUID        `json:"id"`
	SessionID        pgtype.UUID        `json:"session_id"`
	Status           string             `json:"status"`
	CampaignID       string             `json:"campaign_id"`
	KeyVersion       pgtype.Text        `json:"key_version"`
	PayloadNonce     []byte             `json:"payload_nonce"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	AttemptCount     int32              `json:"attempt_count"`
	RunAfter         pgtype.Timestamptz `json:"run_after"`
	LockedBy         pgtype.Text        `json:"locked_by"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
	SubmittingAt     pgtype.Timestamptz `json:"submitting_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	FailedAt         pgtype.Timestamptz `json:"failed_at"`
	UncertainAt      pgtype.Timestamptz `json:"uncertain_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Student struct {
	ID           pgtype.UUID        `json:"id"`
	Wcode        string             `json:"wcode"`
	FullName     string             `json:"full_name"`
	Nickname     pgtype.Text        `json:"nickname"`
	Email        pgtype.Text        `json:"email"`
	StudentPhone pgtype.Text        `json:"student_phone"`
	ParentPhone  pgtype.Text        `json:"parent_phone"`
	Notes        string             `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	EmailCrm     pgtype.Text        `json:"email_crm"`
	EmailSystem  pgtype.Text        `json:"email_system"`
	School       pgtype.Text        `json:"school"`
}

type StudentAbsence struct {
	ID                  pgtype.UUID        `json:"id"`
	Wcode               string             `json:"wcode"`
	CourseID            pgtype.UUID        `json:"course_id"`
	DateFrom            pgtype.Date        `json:"date_from"`
	DateTo              pgtype.Date        `json:"date_to"`
	Reason              pgtype.Text        `json:"reason"`
	SitInCourseID       pgtype.UUID        `json:"sit_in_course_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	SitInMethod         pgtype.Text        `json:"sit_in_method"`
	SubjectID           pgtype.UUID        `json:"subject_id"`
	Status              string             `json:"status"`
	ReasonCategory      pgtype.Text        `json:"reason_category"`
	AdminNotes          pgtype.Text        `json:"admin_notes"`
	StudentName         pgtype.Text        `json:"student_name"`
	StudentEmail        pgtype.Text        `json:"student_email"`
	StudentPhone        pgtype.Text        `json:"student_phone"`
	ReviewedBy          pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt          pgtype.Timestamptz `json:"reviewed_at"`
	SitInOverridden     bool               `json:"sit_in_overridden"`
	SitInOverriddenBy   pgtype.UUID        `json:"sit_in_overridden_by"`
	SitInOverrideReason pgtype.Text        `json:"sit_in_override_reason"`
	Version             int32              `json:"version"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	StudentNickname     pgtype.Text        `json:"student_nickname"`
}

type StudentBusyRange struct {
	ID        pgtype.UUID                      `json:"id"`
	StudentID pgtype.UUID                      `json:"student_id"`
	SessionID pgtype.UUID                      `json:"session_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
}

type StudentOtpLockout struct {
	Wcode        string             `json:"wcode"`
	LockedUntil  pgtype.Timestamptz `json:"locked_until"`
	FailureCount int32              `json:"failure_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type StudentParentVerificationSession struct {
	ID                pgtype.UUID        `json:"id"`
	Wcode             string             `json:"wcode"`
	ParentPhone       string             `json:"parent_phone"`
	Status            string             `json:"status"`
	OtpCodeHash       pgtype.Text        `json:"otp_code_hash"`
	OtpAttemptCount   int32              `json:"otp_attempt_count"`
	OtpLockedUntil    pgtype.Timestamptz `json:"otp_locked_until"`
	OtpLastSentAt     pgtype.Timestamptz `json:"otp_last_sent_at"`
	OtpCodeExpiresAt  pgtype.Timestamptz `json:"otp_code_expires_at"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	ConsumedAt        pgtype.Timestamptz `json:"consumed_at"`
	ConsumedAbsenceID pgtype.UUID        `json:"consumed_absence_id"`
	Version           int32              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Subject struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SubjectActiveCourse struct {
	SubjectID pgtype.UUID        `json:"subject_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TeacherAvailability struct {
	ID        pgtype.UUID                      `json:"id"`
	TeacherID pgtype.UUID                      `json:"teacher_id"`
	StartAt   pgtype.Timestamptz               `json:"start_at"`
	EndAt     pgtype.Timestamptz               `json:"end_at"`
	DeletedAt pgtype.Timestamptz               `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz               `json:"created_at"`
	UpdatedAt pgtype.Timestamptz               `json:"updated_at"`
	TimeRange pgtype.Range[pgtype.Timestamptz] `json:"time_range"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Username        string             `json:"username"`
	Role            string             `json:"role"`
	PasswordHash    string             `json:"password_hash"`
	PasswordVersion int32              `json:"password_version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Email           pgtype.Text        `json:"email"`
}
