// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const roomCreate = `-- name: RoomCreate :one
INSERT INTO rooms (name, capacity)
VALUES ($1, $2)
RETURNING id, name, capacity, created_at, updated_at
`

type RoomCreateParams struct {
	Name     string      `json:"name"`
	Capacity pgtype.Int4 `json:"capacity"`
}

func (q *Queries) RoomCreate(ctx context.Context, arg RoomCreateParams) (Room, error) {
	row := q.db.QueryRow(ctx, roomCreate, arg.Name, arg.Capacity)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const roomDelete = `-- name: RoomDelete :exec
DELETE FROM rooms
WHERE id = $1
`

func (q *Queries) RoomDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, roomDelete, id)
	return err
}

const roomGetByID = `-- name: RoomGetByID :one
SELECT id, name, capacity, created_at, updated_at
FROM rooms
WHERE id = $1
`

func (q *Queries) RoomGetByID(ctx context.Context, id pgtype.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, roomGetByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const roomList = `-- name: RoomList :many
SELECT id, name, capacity, created_at, updated_at
FROM rooms
ORDER BY name ASC
`

func (q *Queries) RoomList(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, roomList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomUpdate = `-- name: RoomUpdate :one
UPDATE rooms
SET name = $2, capacity = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, capacity, created_at, updated_at
`

type RoomUpdateParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Capacity pgtype.Int4 `json:"capacity"`
}

func (q *Queries) RoomUpdate(ctx context.Context, arg RoomUpdateParams) (Room, error) {
	row := q.db.QueryRow(ctx, roomUpdate, arg.ID, arg.Name, arg.Capacity)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
