// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduling_resources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const schedulingResourcesGet = `-- name: SchedulingResourcesGet :one

SELECT
    EXISTS (SELECT 1 FROM courses WHERE courses.id = $1) AS course_exists,
    EXISTS (SELECT 1 FROM users WHERE users.id = $2 AND users.deleted_at IS NULL) AS teacher_exists,
    EXISTS (SELECT 1 FROM users WHERE users.id = $2 AND users.deleted_at IS NULL AND users.role IN ('Admin', 'Teacher')) AS teacher_active,
    EXISTS (SELECT 1 FROM rooms WHERE rooms.id = $3) AS room_exists
`

type SchedulingResourcesGetParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	TeacherID pgtype.UUID `json:"teacher_id"`
	RoomID    pgtype.UUID `json:"room_id"`
}

type SchedulingResourcesGetRow struct {
	CourseExists  bool `json:"course_exists"`
	TeacherExists bool `json:"teacher_exists"`
	TeacherActive bool `json:"teacher_active"`
	RoomExists    bool `json:"room_exists"`
}

// Scheduling resource validation queries for the scheduling domain service.
// Validates all referenced resources (course, teacher, room) in one round trip.
// Returns the complete resource validation state: whether the course, teacher,
// and room exist. Used by the advisory preflight to surface explicit resource
// errors before availability/overlap checks.
func (q *Queries) SchedulingResourcesGet(ctx context.Context, arg SchedulingResourcesGetParams) (SchedulingResourcesGetRow, error) {
	row := q.db.QueryRow(ctx, schedulingResourcesGet, arg.CourseID, arg.TeacherID, arg.RoomID)
	var i SchedulingResourcesGetRow
	err := row.Scan(
		&i.CourseExists,
		&i.TeacherExists,
		&i.TeacherActive,
		&i.RoomExists,
	)
	return i, err
}
