// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduling_locks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const coursesLockOrdered = `-- name: CoursesLockOrdered :many
SELECT id FROM courses WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

func (q *Queries) CoursesLockOrdered(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, coursesLockOrdered, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roomsLockOrdered = `-- name: RoomsLockOrdered :many
SELECT id FROM rooms WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

func (q *Queries) RoomsLockOrdered(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, roomsLockOrdered, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seriesLockOrdered = `-- name: SeriesLockOrdered :many
SELECT id FROM session_series WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

func (q *Queries) SeriesLockOrdered(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, seriesLockOrdered, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsLockOrdered = `-- name: SessionsLockOrdered :many
SELECT id FROM sessions WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

func (q *Queries) SessionsLockOrdered(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, sessionsLockOrdered, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentsLockOrdered = `-- name: StudentsLockOrdered :many
SELECT id FROM students WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

func (q *Queries) StudentsLockOrdered(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, studentsLockOrdered, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersLockOrdered = `-- name: UsersLockOrdered :many
SELECT id FROM users WHERE id = ANY($1::uuid[]) ORDER BY id FOR UPDATE
`

func (q *Queries) UsersLockOrdered(ctx context.Context, ids []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, usersLockOrdered, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
