// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const seriesCreate = `-- name: SeriesCreate :one
INSERT INTO session_series (
  course_id, room_id, teacher_id,
  institute_tz, weekdays, start_local_time, duration_minutes,
  start_date, end_date, count
)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, course_id, room_id, teacher_id, institute_tz, weekdays, start_local_time, duration_minutes, start_date, end_date, count, version, deleted_at, created_at, updated_at
`

type SeriesCreateParams struct {
	CourseID        pgtype.UUID `json:"course_id"`
	RoomID          pgtype.UUID `json:"room_id"`
	TeacherID       pgtype.UUID `json:"teacher_id"`
	InstituteTz     string      `json:"institute_tz"`
	Weekdays        []int16     `json:"weekdays"`
	StartLocalTime  pgtype.Time `json:"start_local_time"`
	DurationMinutes int32       `json:"duration_minutes"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	Count           pgtype.Int4 `json:"count"`
}

type SeriesCreateRow struct {
	ID              pgtype.UUID        `json:"id"`
	CourseID        pgtype.UUID        `json:"course_id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	TeacherID       pgtype.UUID        `json:"teacher_id"`
	InstituteTz     string             `json:"institute_tz"`
	Weekdays        []int16            `json:"weekdays"`
	StartLocalTime  pgtype.Time        `json:"start_local_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Count           pgtype.Int4        `json:"count"`
	Version         int32              `json:"version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SeriesCreate(ctx context.Context, arg SeriesCreateParams) (SeriesCreateRow, error) {
	row := q.db.QueryRow(ctx, seriesCreate,
		arg.CourseID,
		arg.RoomID,
		arg.TeacherID,
		arg.InstituteTz,
		arg.Weekdays,
		arg.StartLocalTime,
		arg.DurationMinutes,
		arg.StartDate,
		arg.EndDate,
		arg.Count,
	)
	var i SeriesCreateRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.InstituteTz,
		&i.Weekdays,
		&i.StartLocalTime,
		&i.DurationMinutes,
		&i.StartDate,
		&i.EndDate,
		&i.Count,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const seriesGetByID = `-- name: SeriesGetByID :one
SELECT id, course_id, room_id, teacher_id, institute_tz, weekdays, start_local_time, duration_minutes, start_date, end_date, count, version, deleted_at, created_at, updated_at
FROM session_series
WHERE id = $1
`

type SeriesGetByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	CourseID        pgtype.UUID        `json:"course_id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	TeacherID       pgtype.UUID        `json:"teacher_id"`
	InstituteTz     string             `json:"institute_tz"`
	Weekdays        []int16            `json:"weekdays"`
	StartLocalTime  pgtype.Time        `json:"start_local_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Count           pgtype.Int4        `json:"count"`
	Version         int32              `json:"version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SeriesGetByID(ctx context.Context, id pgtype.UUID) (SeriesGetByIDRow, error) {
	row := q.db.QueryRow(ctx, seriesGetByID, id)
	var i SeriesGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.InstituteTz,
		&i.Weekdays,
		&i.StartLocalTime,
		&i.DurationMinutes,
		&i.StartDate,
		&i.EndDate,
		&i.Count,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const seriesGetByIDForUpdate = `-- name: SeriesGetByIDForUpdate :one
SELECT id, course_id, room_id, teacher_id, institute_tz, weekdays, start_local_time, duration_minutes, start_date, end_date, count, version, deleted_at, created_at, updated_at
FROM session_series
WHERE id = $1
FOR UPDATE
`

type SeriesGetByIDForUpdateRow struct {
	ID              pgtype.UUID        `json:"id"`
	CourseID        pgtype.UUID        `json:"course_id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	TeacherID       pgtype.UUID        `json:"teacher_id"`
	InstituteTz     string             `json:"institute_tz"`
	Weekdays        []int16            `json:"weekdays"`
	StartLocalTime  pgtype.Time        `json:"start_local_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Count           pgtype.Int4        `json:"count"`
	Version         int32              `json:"version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SeriesGetByIDForUpdate(ctx context.Context, id pgtype.UUID) (SeriesGetByIDForUpdateRow, error) {
	row := q.db.QueryRow(ctx, seriesGetByIDForUpdate, id)
	var i SeriesGetByIDForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.InstituteTz,
		&i.Weekdays,
		&i.StartLocalTime,
		&i.DurationMinutes,
		&i.StartDate,
		&i.EndDate,
		&i.Count,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const seriesUpdateCount = `-- name: SeriesUpdateCount :exec
UPDATE session_series
SET count = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3
`

type SeriesUpdateCountParams struct {
	ID      pgtype.UUID `json:"id"`
	Count   pgtype.Int4 `json:"count"`
	Version int32       `json:"version"`
}

func (q *Queries) SeriesUpdateCount(ctx context.Context, arg SeriesUpdateCountParams) error {
	_, err := q.db.Exec(ctx, seriesUpdateCount, arg.ID, arg.Count, arg.Version)
	return err
}

const seriesUpdateEndDate = `-- name: SeriesUpdateEndDate :exec
UPDATE session_series
SET end_date = $2, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $3
`

type SeriesUpdateEndDateParams struct {
	ID      pgtype.UUID `json:"id"`
	EndDate pgtype.Date `json:"end_date"`
	Version int32       `json:"version"`
}

func (q *Queries) SeriesUpdateEndDate(ctx context.Context, arg SeriesUpdateEndDateParams) error {
	_, err := q.db.Exec(ctx, seriesUpdateEndDate, arg.ID, arg.EndDate, arg.Version)
	return err
}

const seriesUpdateFields = `-- name: SeriesUpdateFields :one
UPDATE session_series
SET course_id = $2,
    room_id = $3,
    teacher_id = $4,
    weekdays = $5,
    start_local_time = $6,
    duration_minutes = $7,
    end_date = $8,
    count = $9,
    updated_at = now(),
    version = version + 1
WHERE id = $1 AND version = $10
RETURNING id, course_id, room_id, teacher_id, institute_tz, weekdays, start_local_time, duration_minutes, start_date, end_date, count, version, deleted_at, created_at, updated_at
`

type SeriesUpdateFieldsParams struct {
	ID              pgtype.UUID `json:"id"`
	CourseID        pgtype.UUID `json:"course_id"`
	RoomID          pgtype.UUID `json:"room_id"`
	TeacherID       pgtype.UUID `json:"teacher_id"`
	Weekdays        []int16     `json:"weekdays"`
	StartLocalTime  pgtype.Time `json:"start_local_time"`
	DurationMinutes int32       `json:"duration_minutes"`
	EndDate         pgtype.Date `json:"end_date"`
	Count           pgtype.Int4 `json:"count"`
	Version         int32       `json:"version"`
}

type SeriesUpdateFieldsRow struct {
	ID              pgtype.UUID        `json:"id"`
	CourseID        pgtype.UUID        `json:"course_id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	TeacherID       pgtype.UUID        `json:"teacher_id"`
	InstituteTz     string             `json:"institute_tz"`
	Weekdays        []int16            `json:"weekdays"`
	StartLocalTime  pgtype.Time        `json:"start_local_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	StartDate       pgtype.Date        `json:"start_date"`
	EndDate         pgtype.Date        `json:"end_date"`
	Count           pgtype.Int4        `json:"count"`
	Version         int32              `json:"version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SeriesUpdateFields(ctx context.Context, arg SeriesUpdateFieldsParams) (SeriesUpdateFieldsRow, error) {
	row := q.db.QueryRow(ctx, seriesUpdateFields,
		arg.ID,
		arg.CourseID,
		arg.RoomID,
		arg.TeacherID,
		arg.Weekdays,
		arg.StartLocalTime,
		arg.DurationMinutes,
		arg.EndDate,
		arg.Count,
		arg.Version,
	)
	var i SeriesUpdateFieldsRow
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.InstituteTz,
		&i.Weekdays,
		&i.StartLocalTime,
		&i.DurationMinutes,
		&i.StartDate,
		&i.EndDate,
		&i.Count,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
