// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_change_impact.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const absenceScheduleIssueGet = `-- name: AbsenceScheduleIssueGet :one
SELECT i.id, i.absence_id, i.issue_type, i.severity, i.status,
       i.source_session_id, i.sit_in_session_id, i.missed_session_id,
       i.first_session_change_id, i.latest_session_change_id,
       i.details_json, i.suggested_resolution_json, i.detected_at,
       i.updated_at, i.resolved_at, i.resolved_by, i.resolution_action,
       i.fingerprint, sa.wcode, sa.student_name, sa.student_email,
       sa.student_phone
FROM absence_schedule_issues i
JOIN student_absences sa ON sa.id = i.absence_id
WHERE i.id = $1
`

type AbsenceScheduleIssueGetRow struct {
	ID                      pgtype.UUID        `json:"id"`
	AbsenceID               pgtype.UUID        `json:"absence_id"`
	IssueType               string             `json:"issue_type"`
	Severity                string             `json:"severity"`
	Status                  string             `json:"status"`
	SourceSessionID         pgtype.UUID        `json:"source_session_id"`
	SitInSessionID          pgtype.UUID        `json:"sit_in_session_id"`
	MissedSessionID         pgtype.UUID        `json:"missed_session_id"`
	FirstSessionChangeID    pgtype.UUID        `json:"first_session_change_id"`
	LatestSessionChangeID   pgtype.UUID        `json:"latest_session_change_id"`
	DetailsJson             []byte             `json:"details_json"`
	SuggestedResolutionJson []byte             `json:"suggested_resolution_json"`
	DetectedAt              pgtype.Timestamptz `json:"detected_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt              pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy              pgtype.UUID        `json:"resolved_by"`
	ResolutionAction        pgtype.Text        `json:"resolution_action"`
	Fingerprint             string             `json:"fingerprint"`
	Wcode                   string             `json:"wcode"`
	StudentName             pgtype.Text        `json:"student_name"`
	StudentEmail            pgtype.Text        `json:"student_email"`
	StudentPhone            pgtype.Text        `json:"student_phone"`
}

func (q *Queries) AbsenceScheduleIssueGet(ctx context.Context, id pgtype.UUID) (AbsenceScheduleIssueGetRow, error) {
	row := q.db.QueryRow(ctx, absenceScheduleIssueGet, id)
	var i AbsenceScheduleIssueGetRow
	err := row.Scan(
		&i.ID,
		&i.AbsenceID,
		&i.IssueType,
		&i.Severity,
		&i.Status,
		&i.SourceSessionID,
		&i.SitInSessionID,
		&i.MissedSessionID,
		&i.FirstSessionChangeID,
		&i.LatestSessionChangeID,
		&i.DetailsJson,
		&i.SuggestedResolutionJson,
		&i.DetectedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.ResolutionAction,
		&i.Fingerprint,
		&i.Wcode,
		&i.StudentName,
		&i.StudentEmail,
		&i.StudentPhone,
	)
	return i, err
}

const absenceScheduleIssueList = `-- name: AbsenceScheduleIssueList :many
SELECT i.id, i.absence_id, i.issue_type, i.severity, i.status,
       i.source_session_id, i.sit_in_session_id, i.missed_session_id,
       i.first_session_change_id, i.latest_session_change_id,
       i.details_json, i.suggested_resolution_json, i.detected_at,
       i.updated_at, i.resolved_at, i.resolved_by, i.resolution_action,
       i.fingerprint, sa.wcode, sa.student_name, sa.student_email,
       sa.student_phone, s.start_at, s.end_at,
       i.issue_version,
       i.assignment_snapshot_at_detection, i.assignment_snapshot_quality,
       i.assignment_snapshot_source,
       asi.assigned_at
FROM absence_schedule_issues i
JOIN student_absences sa ON sa.id = i.absence_id
LEFT JOIN sessions s ON s.id = COALESCE(i.sit_in_session_id, i.missed_session_id, i.source_session_id)
LEFT JOIN absence_sit_ins asi ON asi.absence_id = i.absence_id AND asi.session_id = i.sit_in_session_id
WHERE ($1 = '' OR i.status = $1)
ORDER BY CASE WHEN i.severity = 'critical' THEN 0 ELSE 1 END, i.updated_at DESC
LIMIT $2 OFFSET $3
`

type AbsenceScheduleIssueListParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type AbsenceScheduleIssueListRow struct {
	ID                            pgtype.UUID        `json:"id"`
	AbsenceID                     pgtype.UUID        `json:"absence_id"`
	IssueType                     string             `json:"issue_type"`
	Severity                      string             `json:"severity"`
	Status                        string             `json:"status"`
	SourceSessionID               pgtype.UUID        `json:"source_session_id"`
	SitInSessionID                pgtype.UUID        `json:"sit_in_session_id"`
	MissedSessionID               pgtype.UUID        `json:"missed_session_id"`
	FirstSessionChangeID          pgtype.UUID        `json:"first_session_change_id"`
	LatestSessionChangeID         pgtype.UUID        `json:"latest_session_change_id"`
	DetailsJson                   []byte             `json:"details_json"`
	SuggestedResolutionJson       []byte             `json:"suggested_resolution_json"`
	DetectedAt                    pgtype.Timestamptz `json:"detected_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt                    pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy                    pgtype.UUID        `json:"resolved_by"`
	ResolutionAction              pgtype.Text        `json:"resolution_action"`
	Fingerprint                   string             `json:"fingerprint"`
	Wcode                         string             `json:"wcode"`
	StudentName                   pgtype.Text        `json:"student_name"`
	StudentEmail                  pgtype.Text        `json:"student_email"`
	StudentPhone                  pgtype.Text        `json:"student_phone"`
	StartAt                       pgtype.Timestamptz `json:"start_at"`
	EndAt                         pgtype.Timestamptz `json:"end_at"`
	IssueVersion                  int32              `json:"issue_version"`
	AssignmentSnapshotAtDetection []byte             `json:"assignment_snapshot_at_detection"`
	AssignmentSnapshotQuality     string             `json:"assignment_snapshot_quality"`
	AssignmentSnapshotSource      pgtype.Text        `json:"assignment_snapshot_source"`
	AssignedAt                    pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) AbsenceScheduleIssueList(ctx context.Context, arg AbsenceScheduleIssueListParams) ([]AbsenceScheduleIssueListRow, error) {
	rows, err := q.db.Query(ctx, absenceScheduleIssueList, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbsenceScheduleIssueListRow
	for rows.Next() {
		var i AbsenceScheduleIssueListRow
		if err := rows.Scan(
			&i.ID,
			&i.AbsenceID,
			&i.IssueType,
			&i.Severity,
			&i.Status,
			&i.SourceSessionID,
			&i.SitInSessionID,
			&i.MissedSessionID,
			&i.FirstSessionChangeID,
			&i.LatestSessionChangeID,
			&i.DetailsJson,
			&i.SuggestedResolutionJson,
			&i.DetectedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolutionAction,
			&i.Fingerprint,
			&i.Wcode,
			&i.StudentName,
			&i.StudentEmail,
			&i.StudentPhone,
			&i.StartAt,
			&i.EndAt,
			&i.IssueVersion,
			&i.AssignmentSnapshotAtDetection,
			&i.AssignmentSnapshotQuality,
			&i.AssignmentSnapshotSource,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const absenceScheduleIssueListByAbsence = `-- name: AbsenceScheduleIssueListByAbsence :many
SELECT i.id, i.absence_id, i.issue_type, i.severity, i.status,
       i.source_session_id, i.sit_in_session_id, i.missed_session_id,
       i.first_session_change_id, i.latest_session_change_id,
       i.details_json, i.suggested_resolution_json, i.detected_at,
       i.updated_at, i.resolved_at, i.resolved_by, i.resolution_action,
       i.fingerprint, sa.wcode, sa.student_name, sa.student_email,
       sa.student_phone, s.start_at, s.end_at,
       i.issue_version,
       i.assignment_snapshot_at_detection, i.assignment_snapshot_quality,
       i.assignment_snapshot_source,
       asi.assigned_at
FROM absence_schedule_issues i
JOIN student_absences sa ON sa.id = i.absence_id
LEFT JOIN sessions s ON s.id = COALESCE(i.sit_in_session_id, i.missed_session_id, i.source_session_id)
LEFT JOIN absence_sit_ins asi ON asi.absence_id = i.absence_id AND asi.session_id = i.sit_in_session_id
WHERE i.absence_id = $1
ORDER BY CASE WHEN i.status = 'open' THEN 0 ELSE 1 END,
         CASE WHEN i.severity = 'critical' THEN 0 ELSE 1 END, i.updated_at DESC
`

type AbsenceScheduleIssueListByAbsenceRow struct {
	ID                            pgtype.UUID        `json:"id"`
	AbsenceID                     pgtype.UUID        `json:"absence_id"`
	IssueType                     string             `json:"issue_type"`
	Severity                      string             `json:"severity"`
	Status                        string             `json:"status"`
	SourceSessionID               pgtype.UUID        `json:"source_session_id"`
	SitInSessionID                pgtype.UUID        `json:"sit_in_session_id"`
	MissedSessionID               pgtype.UUID        `json:"missed_session_id"`
	FirstSessionChangeID          pgtype.UUID        `json:"first_session_change_id"`
	LatestSessionChangeID         pgtype.UUID        `json:"latest_session_change_id"`
	DetailsJson                   []byte             `json:"details_json"`
	SuggestedResolutionJson       []byte             `json:"suggested_resolution_json"`
	DetectedAt                    pgtype.Timestamptz `json:"detected_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt                    pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy                    pgtype.UUID        `json:"resolved_by"`
	ResolutionAction              pgtype.Text        `json:"resolution_action"`
	Fingerprint                   string             `json:"fingerprint"`
	Wcode                         string             `json:"wcode"`
	StudentName                   pgtype.Text        `json:"student_name"`
	StudentEmail                  pgtype.Text        `json:"student_email"`
	StudentPhone                  pgtype.Text        `json:"student_phone"`
	StartAt                       pgtype.Timestamptz `json:"start_at"`
	EndAt                         pgtype.Timestamptz `json:"end_at"`
	IssueVersion                  int32              `json:"issue_version"`
	AssignmentSnapshotAtDetection []byte             `json:"assignment_snapshot_at_detection"`
	AssignmentSnapshotQuality     string             `json:"assignment_snapshot_quality"`
	AssignmentSnapshotSource      pgtype.Text        `json:"assignment_snapshot_source"`
	AssignedAt                    pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) AbsenceScheduleIssueListByAbsence(ctx context.Context, absenceID pgtype.UUID) ([]AbsenceScheduleIssueListByAbsenceRow, error) {
	rows, err := q.db.Query(ctx, absenceScheduleIssueListByAbsence, absenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbsenceScheduleIssueListByAbsenceRow
	for rows.Next() {
		var i AbsenceScheduleIssueListByAbsenceRow
		if err := rows.Scan(
			&i.ID,
			&i.AbsenceID,
			&i.IssueType,
			&i.Severity,
			&i.Status,
			&i.SourceSessionID,
			&i.SitInSessionID,
			&i.MissedSessionID,
			&i.FirstSessionChangeID,
			&i.LatestSessionChangeID,
			&i.DetailsJson,
			&i.SuggestedResolutionJson,
			&i.DetectedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolutionAction,
			&i.Fingerprint,
			&i.Wcode,
			&i.StudentName,
			&i.StudentEmail,
			&i.StudentPhone,
			&i.StartAt,
			&i.EndAt,
			&i.IssueVersion,
			&i.AssignmentSnapshotAtDetection,
			&i.AssignmentSnapshotQuality,
			&i.AssignmentSnapshotSource,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const absenceScheduleIssueListByChange = `-- name: AbsenceScheduleIssueListByChange :many
SELECT i.id, i.absence_id, i.issue_type, i.severity, i.status,
       i.source_session_id, i.sit_in_session_id, i.missed_session_id,
       i.first_session_change_id, i.latest_session_change_id,
       i.details_json, i.suggested_resolution_json, i.detected_at,
       i.updated_at, i.resolved_at, i.resolved_by, i.resolution_action,
       i.fingerprint, sa.wcode, sa.student_name, sa.student_email,
       sa.student_phone, s.start_at, s.end_at,
       i.issue_version,
       i.assignment_snapshot_at_detection, i.assignment_snapshot_quality,
       i.assignment_snapshot_source,
       asi.assigned_at
FROM absence_schedule_issues i
JOIN student_absences sa ON sa.id = i.absence_id
LEFT JOIN sessions s ON s.id = COALESCE(i.sit_in_session_id, i.missed_session_id, i.source_session_id)
LEFT JOIN absence_sit_ins asi ON asi.absence_id = i.absence_id AND asi.session_id = i.sit_in_session_id
WHERE i.latest_session_change_id = $1
ORDER BY CASE WHEN i.severity = 'critical' THEN 0 ELSE 1 END, i.updated_at DESC
`

type AbsenceScheduleIssueListByChangeRow struct {
	ID                            pgtype.UUID        `json:"id"`
	AbsenceID                     pgtype.UUID        `json:"absence_id"`
	IssueType                     string             `json:"issue_type"`
	Severity                      string             `json:"severity"`
	Status                        string             `json:"status"`
	SourceSessionID               pgtype.UUID        `json:"source_session_id"`
	SitInSessionID                pgtype.UUID        `json:"sit_in_session_id"`
	MissedSessionID               pgtype.UUID        `json:"missed_session_id"`
	FirstSessionChangeID          pgtype.UUID        `json:"first_session_change_id"`
	LatestSessionChangeID         pgtype.UUID        `json:"latest_session_change_id"`
	DetailsJson                   []byte             `json:"details_json"`
	SuggestedResolutionJson       []byte             `json:"suggested_resolution_json"`
	DetectedAt                    pgtype.Timestamptz `json:"detected_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
	ResolvedAt                    pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy                    pgtype.UUID        `json:"resolved_by"`
	ResolutionAction              pgtype.Text        `json:"resolution_action"`
	Fingerprint                   string             `json:"fingerprint"`
	Wcode                         string             `json:"wcode"`
	StudentName                   pgtype.Text        `json:"student_name"`
	StudentEmail                  pgtype.Text        `json:"student_email"`
	StudentPhone                  pgtype.Text        `json:"student_phone"`
	StartAt                       pgtype.Timestamptz `json:"start_at"`
	EndAt                         pgtype.Timestamptz `json:"end_at"`
	IssueVersion                  int32              `json:"issue_version"`
	AssignmentSnapshotAtDetection []byte             `json:"assignment_snapshot_at_detection"`
	AssignmentSnapshotQuality     string             `json:"assignment_snapshot_quality"`
	AssignmentSnapshotSource      pgtype.Text        `json:"assignment_snapshot_source"`
	AssignedAt                    pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) AbsenceScheduleIssueListByChange(ctx context.Context, latestSessionChangeID pgtype.UUID) ([]AbsenceScheduleIssueListByChangeRow, error) {
	rows, err := q.db.Query(ctx, absenceScheduleIssueListByChange, latestSessionChangeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbsenceScheduleIssueListByChangeRow
	for rows.Next() {
		var i AbsenceScheduleIssueListByChangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AbsenceID,
			&i.IssueType,
			&i.Severity,
			&i.Status,
			&i.SourceSessionID,
			&i.SitInSessionID,
			&i.MissedSessionID,
			&i.FirstSessionChangeID,
			&i.LatestSessionChangeID,
			&i.DetailsJson,
			&i.SuggestedResolutionJson,
			&i.DetectedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.ResolutionAction,
			&i.Fingerprint,
			&i.Wcode,
			&i.StudentName,
			&i.StudentEmail,
			&i.StudentPhone,
			&i.StartAt,
			&i.EndAt,
			&i.IssueVersion,
			&i.AssignmentSnapshotAtDetection,
			&i.AssignmentSnapshotQuality,
			&i.AssignmentSnapshotSource,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const absenceScheduleIssueResolve = `-- name: AbsenceScheduleIssueResolve :exec
UPDATE absence_schedule_issues
SET status = $2, resolved_at = now(), resolved_by = $3,
    resolution_action = $4, updated_at = now()
WHERE id = $1 AND status IN ('open', 'needs_review')
`

type AbsenceScheduleIssueResolveParams struct {
	ID               pgtype.UUID `json:"id"`
	Status           string      `json:"status"`
	ResolvedBy       pgtype.UUID `json:"resolved_by"`
	ResolutionAction pgtype.Text `json:"resolution_action"`
}

func (q *Queries) AbsenceScheduleIssueResolve(ctx context.Context, arg AbsenceScheduleIssueResolveParams) error {
	_, err := q.db.Exec(ctx, absenceScheduleIssueResolve,
		arg.ID,
		arg.Status,
		arg.ResolvedBy,
		arg.ResolutionAction,
	)
	return err
}

const absenceScheduleIssueUpsert = `-- name: AbsenceScheduleIssueUpsert :one
INSERT INTO absence_schedule_issues (
  absence_id, issue_type, severity, status, source_session_id, sit_in_session_id,
  missed_session_id, first_session_change_id, latest_session_change_id,
  details_json, suggested_resolution_json, fingerprint,
  assignment_snapshot_at_detection, assignment_snapshot_quality, assignment_snapshot_source
)
VALUES (
  $1,
  $2,
  $3,
  'open',
  $4,
  $5,
  $6,
  $7,
  $7,
  $8::text::jsonb,
  $9::text::jsonb,
  $10,
  $11::text::jsonb,
  $12,
  $13
)
ON CONFLICT (fingerprint) WHERE status IN ('open', 'needs_review')
DO UPDATE SET severity = EXCLUDED.severity,
              latest_session_change_id = EXCLUDED.latest_session_change_id,
              details_json = EXCLUDED.details_json,
              suggested_resolution_json = EXCLUDED.suggested_resolution_json,
              issue_version = absence_schedule_issues.issue_version + 1,
              updated_at = now()
WHERE absence_schedule_issues.severity IS DISTINCT FROM EXCLUDED.severity
   OR absence_schedule_issues.latest_session_change_id IS DISTINCT FROM EXCLUDED.latest_session_change_id
   OR absence_schedule_issues.details_json IS DISTINCT FROM EXCLUDED.details_json
   OR absence_schedule_issues.suggested_resolution_json IS DISTINCT FROM EXCLUDED.suggested_resolution_json
RETURNING id
`

type AbsenceScheduleIssueUpsertParams struct {
	AbsenceID               pgtype.UUID `json:"absence_id"`
	IssueType               string      `json:"issue_type"`
	Severity                string      `json:"severity"`
	SourceSessionID         pgtype.UUID `json:"source_session_id"`
	SitInSessionID          pgtype.UUID `json:"sit_in_session_id"`
	MissedSessionID         pgtype.UUID `json:"missed_session_id"`
	SessionChangeID         pgtype.UUID `json:"session_change_id"`
	DetailsJson             string      `json:"details_json"`
	SuggestedResolutionJson string      `json:"suggested_resolution_json"`
	Fingerprint             string      `json:"fingerprint"`
	SnapshotJson            string      `json:"snapshot_json"`
	SnapshotQuality         string      `json:"snapshot_quality"`
	SnapshotSource          pgtype.Text `json:"snapshot_source"`
}

func (q *Queries) AbsenceScheduleIssueUpsert(ctx context.Context, arg AbsenceScheduleIssueUpsertParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, absenceScheduleIssueUpsert,
		arg.AbsenceID,
		arg.IssueType,
		arg.Severity,
		arg.SourceSessionID,
		arg.SitInSessionID,
		arg.MissedSessionID,
		arg.SessionChangeID,
		arg.DetailsJson,
		arg.SuggestedResolutionJson,
		arg.Fingerprint,
		arg.SnapshotJson,
		arg.SnapshotQuality,
		arg.SnapshotSource,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const notificationOutboxInsert = `-- name: NotificationOutboxInsert :exec
INSERT INTO notification_outbox (
  absence_id, assignment_id, session_version, message_type, recipient,
  channel, payload, idempotency_key
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7::text::jsonb,
  $8
)
ON CONFLICT (idempotency_key) DO NOTHING
`

type NotificationOutboxInsertParams struct {
	AbsenceID      pgtype.UUID `json:"absence_id"`
	AssignmentID   pgtype.UUID `json:"assignment_id"`
	SessionVersion int32       `json:"session_version"`
	MessageType    string      `json:"message_type"`
	Recipient      string      `json:"recipient"`
	Channel        string      `json:"channel"`
	Payload        string      `json:"payload"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) NotificationOutboxInsert(ctx context.Context, arg NotificationOutboxInsertParams) error {
	_, err := q.db.Exec(ctx, notificationOutboxInsert,
		arg.AbsenceID,
		arg.AssignmentID,
		arg.SessionVersion,
		arg.MessageType,
		arg.Recipient,
		arg.Channel,
		arg.Payload,
		arg.IdempotencyKey,
	)
	return err
}

const outboxClaimNext = `-- name: OutboxClaimNext :one
WITH candidate AS (
  SELECT id
  FROM outbox_events
  WHERE (status = 'pending' AND available_at <= now())
     OR (status = 'processing' AND locked_until < now())
  ORDER BY created_at ASC
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
UPDATE outbox_events AS event
SET status = 'processing',
    attempts = event.attempts + 1,
    locked_until = now() + interval '60 seconds'
FROM candidate
WHERE event.id = candidate.id
RETURNING event.id, event.event_type, event.aggregate_id, event.aggregate_version,
          event.payload, event.attempts
`

type OutboxClaimNextRow struct {
	ID               pgtype.UUID `json:"id"`
	EventType        string      `json:"event_type"`
	AggregateID      pgtype.UUID `json:"aggregate_id"`
	AggregateVersion int32       `json:"aggregate_version"`
	Payload          []byte      `json:"payload"`
	Attempts         int32       `json:"attempts"`
}

func (q *Queries) OutboxClaimNext(ctx context.Context) (OutboxClaimNextRow, error) {
	row := q.db.QueryRow(ctx, outboxClaimNext)
	var i OutboxClaimNextRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.Attempts,
	)
	return i, err
}

const outboxComplete = `-- name: OutboxComplete :exec
UPDATE outbox_events
SET status = 'completed', locked_until = NULL, processed_at = now(), last_error = NULL
WHERE id = $1
`

func (q *Queries) OutboxComplete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, outboxComplete, id)
	return err
}

const outboxEventInsert = `-- name: OutboxEventInsert :exec
INSERT INTO outbox_events (event_type, aggregate_id, aggregate_version, payload)
VALUES (
  $1,
  $2,
  $3,
  $4::text::jsonb
)
ON CONFLICT (event_type, aggregate_id, aggregate_version) DO NOTHING
`

type OutboxEventInsertParams struct {
	EventType        string      `json:"event_type"`
	AggregateID      pgtype.UUID `json:"aggregate_id"`
	AggregateVersion int32       `json:"aggregate_version"`
	Payload          string      `json:"payload"`
}

func (q *Queries) OutboxEventInsert(ctx context.Context, arg OutboxEventInsertParams) error {
	_, err := q.db.Exec(ctx, outboxEventInsert,
		arg.EventType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
	)
	return err
}

const outboxRetry = `-- name: OutboxRetry :exec
UPDATE outbox_events
SET status = CASE WHEN attempts >= $2 THEN 'failed' ELSE 'pending' END,
    available_at = now() + $3::interval,
    locked_until = NULL,
    last_error = $4
WHERE id = $1
`

type OutboxRetryParams struct {
	ID        pgtype.UUID     `json:"id"`
	Attempts  int32           `json:"attempts"`
	Column3   pgtype.Interval `json:"column_3"`
	LastError pgtype.Text     `json:"last_error"`
}

func (q *Queries) OutboxRetry(ctx context.Context, arg OutboxRetryParams) error {
	_, err := q.db.Exec(ctx, outboxRetry,
		arg.ID,
		arg.Attempts,
		arg.Column3,
		arg.LastError,
	)
	return err
}

const sessionChangeAffectedAbsences = `-- name: SessionChangeAffectedAbsences :many
WITH targets AS (
  SELECT absence_id, relation_type
  FROM session_change_impact_targets
  WHERE session_change_id = $1
)
SELECT DISTINCT sa.id, sa.wcode, sa.student_name, sa.student_email, sa.student_phone,
       asi.id AS assignment_id, asi.session_id AS sit_in_session_id,
       ams.session_id AS missed_session_id,
       s.id AS affected_session_id, s.version AS affected_session_version,
       s.start_at, s.end_at, s.course_id, COALESCE(targets.relation_type, '') AS impact_relation,
       asi.session_snapshot_at_assignment AS assignment_snapshot_json,
       asi.snapshot_quality AS assignment_snapshot_quality,
       asi.snapshot_source AS assignment_snapshot_source
FROM session_changes sc
JOIN student_absences sa ON (
  EXISTS (SELECT 1 FROM absence_sit_ins x WHERE x.absence_id = sa.id AND x.session_id = sc.session_id)
  OR EXISTS (SELECT 1 FROM absence_missed_sessions x WHERE x.absence_id = sa.id AND x.session_id = sc.session_id)
  OR EXISTS (SELECT 1 FROM absence_sit_ins x JOIN sessions x_session ON x_session.id = x.session_id WHERE x.absence_id = sa.id AND x_session.course_id IN (sc.old_course_id, sc.new_course_id))
  OR EXISTS (SELECT 1 FROM absence_schedule_issues x WHERE x.absence_id = sa.id AND x.status IN ('open', 'needs_review') AND (x.source_session_id = sc.session_id OR x.sit_in_session_id = sc.session_id OR x.missed_session_id = sc.session_id))
  OR EXISTS (SELECT 1 FROM course_students cs WHERE cs.student_id = (SELECT st.id FROM students st WHERE st.wcode = sa.wcode LIMIT 1) AND cs.course_id IN (sc.old_course_id, sc.new_course_id))
  OR EXISTS (SELECT 1 FROM targets target WHERE target.absence_id = sa.id)
)
LEFT JOIN targets ON targets.absence_id = sa.id
LEFT JOIN absence_sit_ins asi ON asi.absence_id = sa.id AND asi.session_id = sc.session_id
LEFT JOIN absence_missed_sessions ams ON ams.absence_id = sa.id AND ams.session_id = sc.session_id
LEFT JOIN sessions s ON s.id = COALESCE(asi.session_id, ams.session_id, sc.session_id)
WHERE sc.id = $1
`

type SessionChangeAffectedAbsencesRow struct {
	ID                        pgtype.UUID        `json:"id"`
	Wcode                     string             `json:"wcode"`
	StudentName               pgtype.Text        `json:"student_name"`
	StudentEmail              pgtype.Text        `json:"student_email"`
	StudentPhone              pgtype.Text        `json:"student_phone"`
	AssignmentID              pgtype.UUID        `json:"assignment_id"`
	SitInSessionID            pgtype.UUID        `json:"sit_in_session_id"`
	MissedSessionID           pgtype.UUID        `json:"missed_session_id"`
	AffectedSessionID         pgtype.UUID        `json:"affected_session_id"`
	AffectedSessionVersion    pgtype.Int4        `json:"affected_session_version"`
	StartAt                   pgtype.Timestamptz `json:"start_at"`
	EndAt                     pgtype.Timestamptz `json:"end_at"`
	CourseID                  pgtype.UUID        `json:"course_id"`
	ImpactRelation            string             `json:"impact_relation"`
	AssignmentSnapshotJson    []byte             `json:"assignment_snapshot_json"`
	AssignmentSnapshotQuality pgtype.Text        `json:"assignment_snapshot_quality"`
	AssignmentSnapshotSource  pgtype.Text        `json:"assignment_snapshot_source"`
}

func (q *Queries) SessionChangeAffectedAbsences(ctx context.Context, id pgtype.UUID) ([]SessionChangeAffectedAbsencesRow, error) {
	rows, err := q.db.Query(ctx, sessionChangeAffectedAbsences, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionChangeAffectedAbsencesRow
	for rows.Next() {
		var i SessionChangeAffectedAbsencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Wcode,
			&i.StudentName,
			&i.StudentEmail,
			&i.StudentPhone,
			&i.AssignmentID,
			&i.SitInSessionID,
			&i.MissedSessionID,
			&i.AffectedSessionID,
			&i.AffectedSessionVersion,
			&i.StartAt,
			&i.EndAt,
			&i.CourseID,
			&i.ImpactRelation,
			&i.AssignmentSnapshotJson,
			&i.AssignmentSnapshotQuality,
			&i.AssignmentSnapshotSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionChangeGetByID = `-- name: SessionChangeGetByID :one
SELECT sc.id, sc.session_id, sc.session_version, sc.batch_id, sc.changed_by,
       sc.change_source, sc.changed_fields, sc.before_snapshot, sc.after_snapshot,
       sc.old_start_at, sc.old_end_at, sc.new_start_at, sc.new_end_at,
       sc.old_course_id, COALESCE(old_course.code, ''), COALESCE(old_course.name, ''),
       sc.new_course_id, COALESCE(new_course.code, ''), COALESCE(new_course.name, ''),
       sc.old_room_id, old_room.name,
       sc.new_room_id, new_room.name,
       sc.old_teacher_id, COALESCE(old_teacher.username, ''),
       sc.new_teacher_id, COALESCE(new_teacher.username, ''),
       sc.created_at,
       (SELECT count(*)::int4 FROM absence_schedule_issues i WHERE i.latest_session_change_id = sc.id AND i.status = 'open') AS open_issue_count,
       (SELECT count(*)::int4 FROM absence_schedule_issues i WHERE i.latest_session_change_id = sc.id AND i.status = 'open' AND i.severity = 'critical') AS critical_issue_count
FROM session_changes sc
LEFT JOIN courses old_course ON old_course.id = sc.old_course_id
LEFT JOIN courses new_course ON new_course.id = sc.new_course_id
LEFT JOIN rooms old_room ON old_room.id = sc.old_room_id
LEFT JOIN rooms new_room ON new_room.id = sc.new_room_id
LEFT JOIN users old_teacher ON old_teacher.id = sc.old_teacher_id
LEFT JOIN users new_teacher ON new_teacher.id = sc.new_teacher_id
WHERE sc.id = $1
`

type SessionChangeGetByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	SessionVersion     int32              `json:"session_version"`
	BatchID            pgtype.UUID        `json:"batch_id"`
	ChangedBy          pgtype.UUID        `json:"changed_by"`
	ChangeSource       string             `json:"change_source"`
	ChangedFields      []byte             `json:"changed_fields"`
	BeforeSnapshot     []byte             `json:"before_snapshot"`
	AfterSnapshot      []byte             `json:"after_snapshot"`
	OldStartAt         pgtype.Timestamptz `json:"old_start_at"`
	OldEndAt           pgtype.Timestamptz `json:"old_end_at"`
	NewStartAt         pgtype.Timestamptz `json:"new_start_at"`
	NewEndAt           pgtype.Timestamptz `json:"new_end_at"`
	OldCourseID        pgtype.UUID        `json:"old_course_id"`
	Code               string             `json:"code"`
	Name               string             `json:"name"`
	NewCourseID        pgtype.UUID        `json:"new_course_id"`
	Code_2             string             `json:"code_2"`
	Name_2             string             `json:"name_2"`
	OldRoomID          pgtype.UUID        `json:"old_room_id"`
	Name_3             pgtype.Text        `json:"name_3"`
	NewRoomID          pgtype.UUID        `json:"new_room_id"`
	Name_4             pgtype.Text        `json:"name_4"`
	OldTeacherID       pgtype.UUID        `json:"old_teacher_id"`
	Username           string             `json:"username"`
	NewTeacherID       pgtype.UUID        `json:"new_teacher_id"`
	Username_2         string             `json:"username_2"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OpenIssueCount     int32              `json:"open_issue_count"`
	CriticalIssueCount int32              `json:"critical_issue_count"`
}

func (q *Queries) SessionChangeGetByID(ctx context.Context, id pgtype.UUID) (SessionChangeGetByIDRow, error) {
	row := q.db.QueryRow(ctx, sessionChangeGetByID, id)
	var i SessionChangeGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SessionVersion,
		&i.BatchID,
		&i.ChangedBy,
		&i.ChangeSource,
		&i.ChangedFields,
		&i.BeforeSnapshot,
		&i.AfterSnapshot,
		&i.OldStartAt,
		&i.OldEndAt,
		&i.NewStartAt,
		&i.NewEndAt,
		&i.OldCourseID,
		&i.Code,
		&i.Name,
		&i.NewCourseID,
		&i.Code_2,
		&i.Name_2,
		&i.OldRoomID,
		&i.Name_3,
		&i.NewRoomID,
		&i.Name_4,
		&i.OldTeacherID,
		&i.Username,
		&i.NewTeacherID,
		&i.Username_2,
		&i.CreatedAt,
		&i.OpenIssueCount,
		&i.CriticalIssueCount,
	)
	return i, err
}

const sessionChangeInsert = `-- name: SessionChangeInsert :one
INSERT INTO session_changes (
  session_id, session_version, batch_id, changed_by, change_source,
  changed_fields, before_snapshot, after_snapshot,
  old_start_at, old_end_at, new_start_at, new_end_at,
  old_course_id, new_course_id, old_room_id, new_room_id,
  old_teacher_id, new_teacher_id
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6::text::jsonb,
  $7::text::jsonb,
  $8::text::jsonb,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18
)
RETURNING id, session_id, session_version, batch_id, changed_by, change_source,
          changed_fields, before_snapshot, after_snapshot, created_at
`

type SessionChangeInsertParams struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	SessionVersion int32              `json:"session_version"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	ChangedBy      pgtype.UUID        `json:"changed_by"`
	ChangeSource   string             `json:"change_source"`
	ChangedFields  string             `json:"changed_fields"`
	BeforeSnapshot string             `json:"before_snapshot"`
	AfterSnapshot  string             `json:"after_snapshot"`
	OldStartAt     pgtype.Timestamptz `json:"old_start_at"`
	OldEndAt       pgtype.Timestamptz `json:"old_end_at"`
	NewStartAt     pgtype.Timestamptz `json:"new_start_at"`
	NewEndAt       pgtype.Timestamptz `json:"new_end_at"`
	OldCourseID    pgtype.UUID        `json:"old_course_id"`
	NewCourseID    pgtype.UUID        `json:"new_course_id"`
	OldRoomID      pgtype.UUID        `json:"old_room_id"`
	NewRoomID      pgtype.UUID        `json:"new_room_id"`
	OldTeacherID   pgtype.UUID        `json:"old_teacher_id"`
	NewTeacherID   pgtype.UUID        `json:"new_teacher_id"`
}

type SessionChangeInsertRow struct {
	ID             pgtype.UUID        `json:"id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	SessionVersion int32              `json:"session_version"`
	BatchID        pgtype.UUID        `json:"batch_id"`
	ChangedBy      pgtype.UUID        `json:"changed_by"`
	ChangeSource   string             `json:"change_source"`
	ChangedFields  []byte             `json:"changed_fields"`
	BeforeSnapshot []byte             `json:"before_snapshot"`
	AfterSnapshot  []byte             `json:"after_snapshot"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SessionChangeInsert(ctx context.Context, arg SessionChangeInsertParams) (SessionChangeInsertRow, error) {
	row := q.db.QueryRow(ctx, sessionChangeInsert,
		arg.SessionID,
		arg.SessionVersion,
		arg.BatchID,
		arg.ChangedBy,
		arg.ChangeSource,
		arg.ChangedFields,
		arg.BeforeSnapshot,
		arg.AfterSnapshot,
		arg.OldStartAt,
		arg.OldEndAt,
		arg.NewStartAt,
		arg.NewEndAt,
		arg.OldCourseID,
		arg.NewCourseID,
		arg.OldRoomID,
		arg.NewRoomID,
		arg.OldTeacherID,
		arg.NewTeacherID,
	)
	var i SessionChangeInsertRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SessionVersion,
		&i.BatchID,
		&i.ChangedBy,
		&i.ChangeSource,
		&i.ChangedFields,
		&i.BeforeSnapshot,
		&i.AfterSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const sessionChangeList = `-- name: SessionChangeList :many
SELECT sc.id, sc.session_id, sc.session_version, sc.changed_by, sc.change_source,
       sc.old_start_at, sc.old_end_at, sc.new_start_at, sc.new_end_at,
       COALESCE(old_course.code, ''), COALESCE(old_course.name, ''),
       COALESCE(new_course.code, ''), COALESCE(new_course.name, ''),
       COALESCE(new_subject.name, '') AS new_course_subject,
       sc.created_at,
       count(i.id) FILTER (WHERE i.status = 'open')::int4 AS open_issue_count,
       count(i.id) FILTER (WHERE i.status = 'open' AND i.severity = 'critical')::int4 AS critical_issue_count
FROM session_changes sc
LEFT JOIN courses old_course ON old_course.id = sc.old_course_id
LEFT JOIN courses new_course ON new_course.id = sc.new_course_id
LEFT JOIN subjects new_subject ON new_subject.id = new_course.subject_id
LEFT JOIN absence_schedule_issues i ON i.latest_session_change_id = sc.id
GROUP BY sc.id, old_course.code, old_course.name, new_course.code, new_course.name, new_subject.name
ORDER BY sc.created_at DESC
LIMIT $1 OFFSET $2
`

type SessionChangeListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type SessionChangeListRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	SessionVersion     int32              `json:"session_version"`
	ChangedBy          pgtype.UUID        `json:"changed_by"`
	ChangeSource       string             `json:"change_source"`
	OldStartAt         pgtype.Timestamptz `json:"old_start_at"`
	OldEndAt           pgtype.Timestamptz `json:"old_end_at"`
	NewStartAt         pgtype.Timestamptz `json:"new_start_at"`
	NewEndAt           pgtype.Timestamptz `json:"new_end_at"`
	Code               string             `json:"code"`
	Name               string             `json:"name"`
	Code_2             string             `json:"code_2"`
	Name_2             string             `json:"name_2"`
	NewCourseSubject   string             `json:"new_course_subject"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	OpenIssueCount     int32              `json:"open_issue_count"`
	CriticalIssueCount int32              `json:"critical_issue_count"`
}

func (q *Queries) SessionChangeList(ctx context.Context, arg SessionChangeListParams) ([]SessionChangeListRow, error) {
	rows, err := q.db.Query(ctx, sessionChangeList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionChangeListRow
	for rows.Next() {
		var i SessionChangeListRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SessionVersion,
			&i.ChangedBy,
			&i.ChangeSource,
			&i.OldStartAt,
			&i.OldEndAt,
			&i.NewStartAt,
			&i.NewEndAt,
			&i.Code,
			&i.Name,
			&i.Code_2,
			&i.Name_2,
			&i.NewCourseSubject,
			&i.CreatedAt,
			&i.OpenIssueCount,
			&i.CriticalIssueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sitInAssignmentFacts = `-- name: SitInAssignmentFacts :one
SELECT asi.id, asi.absence_id, asi.session_id,
       sit.version, asi.session_version_at_assignment,
       sit.deleted_at, sit.start_at, sit.end_at,
       EXISTS (
         SELECT 1
         FROM absence_missed_sessions ams
         JOIN sessions missed ON missed.id = ams.session_id
         WHERE ams.absence_id = asi.absence_id
           AND missed.deleted_at IS NULL
           AND sit.start_at < missed.end_at
           AND sit.end_at > missed.start_at
       ) AS missed_overlap,
       EXISTS (
         SELECT 1
         FROM student_absences sa
         JOIN students st ON st.wcode = sa.wcode
         JOIN course_students cs ON cs.student_id = st.id AND cs.status = 'enrolled'
         JOIN sessions normal ON normal.course_id = cs.course_id AND normal.deleted_at IS NULL
         WHERE sa.id = asi.absence_id
           AND normal.id <> sit.id
           AND student_is_expected_at_session(st.id, normal.id)
           AND sit.start_at < normal.end_at
           AND sit.end_at > normal.start_at
       ) AS normal_overlap,
       EXISTS (
         SELECT 1
         FROM absence_sit_ins other_assignment
         JOIN sessions other_session ON other_session.id = other_assignment.session_id
         WHERE other_assignment.absence_id = asi.absence_id
           AND other_assignment.id <> asi.id
           AND other_session.deleted_at IS NULL
           AND sit.start_at < other_session.end_at
           AND sit.end_at > other_session.start_at
       ) AS sit_in_overlap
FROM absence_sit_ins asi
JOIN sessions sit ON sit.id = asi.session_id
WHERE asi.absence_id = $1 AND asi.session_id = $2
`

type SitInAssignmentFactsParams struct {
	AbsenceID pgtype.UUID `json:"absence_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type SitInAssignmentFactsRow struct {
	ID                         pgtype.UUID        `json:"id"`
	AbsenceID                  pgtype.UUID        `json:"absence_id"`
	SessionID                  pgtype.UUID        `json:"session_id"`
	Version                    int32              `json:"version"`
	SessionVersionAtAssignment pgtype.Int4        `json:"session_version_at_assignment"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	StartAt                    pgtype.Timestamptz `json:"start_at"`
	EndAt                      pgtype.Timestamptz `json:"end_at"`
	MissedOverlap              bool               `json:"missed_overlap"`
	NormalOverlap              bool               `json:"normal_overlap"`
	SitInOverlap               bool               `json:"sit_in_overlap"`
}

func (q *Queries) SitInAssignmentFacts(ctx context.Context, arg SitInAssignmentFactsParams) (SitInAssignmentFactsRow, error) {
	row := q.db.QueryRow(ctx, sitInAssignmentFacts, arg.AbsenceID, arg.SessionID)
	var i SitInAssignmentFactsRow
	err := row.Scan(
		&i.ID,
		&i.AbsenceID,
		&i.SessionID,
		&i.Version,
		&i.SessionVersionAtAssignment,
		&i.DeletedAt,
		&i.StartAt,
		&i.EndAt,
		&i.MissedOverlap,
		&i.NormalOverlap,
		&i.SitInOverlap,
	)
	return i, err
}
