// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionAttendanceDelete = `-- name: SessionAttendanceDelete :exec
DELETE FROM session_attendance
WHERE session_id = $1 AND student_id = $2
`

type SessionAttendanceDeleteParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) SessionAttendanceDelete(ctx context.Context, arg SessionAttendanceDeleteParams) error {
	_, err := q.db.Exec(ctx, sessionAttendanceDelete, arg.SessionID, arg.StudentID)
	return err
}

const sessionAttendanceDeleteNotInCourse = `-- name: SessionAttendanceDeleteNotInCourse :exec
DELETE FROM session_attendance sa
WHERE sa.session_id = $1
  AND NOT EXISTS (
    SELECT 1
    FROM course_students cs
    WHERE cs.course_id = $2
      AND cs.student_id = sa.student_id
  )
`

type SessionAttendanceDeleteNotInCourseParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	CourseID  pgtype.UUID `json:"course_id"`
}

func (q *Queries) SessionAttendanceDeleteNotInCourse(ctx context.Context, arg SessionAttendanceDeleteNotInCourseParams) error {
	_, err := q.db.Exec(ctx, sessionAttendanceDeleteNotInCourse, arg.SessionID, arg.CourseID)
	return err
}

const sessionAttendanceList = `-- name: SessionAttendanceList :many
SELECT session_id, student_id, status, created_at
FROM session_attendance
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) SessionAttendanceList(ctx context.Context, sessionID pgtype.UUID) ([]SessionAttendance, error) {
	rows, err := q.db.Query(ctx, sessionAttendanceList, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAttendance
	for rows.Next() {
		var i SessionAttendance
		if err := rows.Scan(
			&i.SessionID,
			&i.StudentID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionAttendanceUpsert = `-- name: SessionAttendanceUpsert :exec
INSERT INTO session_attendance (session_id, student_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (session_id, student_id) DO UPDATE SET status = EXCLUDED.status
`

type SessionAttendanceUpsertParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	StudentID pgtype.UUID `json:"student_id"`
	Status    string      `json:"status"`
}

func (q *Queries) SessionAttendanceUpsert(ctx context.Context, arg SessionAttendanceUpsertParams) error {
	_, err := q.db.Exec(ctx, sessionAttendanceUpsert, arg.SessionID, arg.StudentID, arg.Status)
	return err
}

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions (series_id, course_id, room_id, teacher_id, start_at, end_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, series_id, course_id, room_id, teacher_id, start_at, end_at, version, deleted_at, created_at, updated_at
`

type SessionCreateParams struct {
	SeriesID  pgtype.UUID        `json:"series_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
}

type SessionCreateRow struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Version   int32              `json:"version"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (SessionCreateRow, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.SeriesID,
		arg.CourseID,
		arg.RoomID,
		arg.TeacherID,
		arg.StartAt,
		arg.EndAt,
	)
	var i SessionCreateRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionGetByID = `-- name: SessionGetByID :one
SELECT id, series_id, course_id, room_id, teacher_id, start_at, end_at, version, deleted_at, created_at, updated_at
FROM sessions
WHERE id = $1
`

type SessionGetByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Version   int32              `json:"version"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionGetByID(ctx context.Context, id pgtype.UUID) (SessionGetByIDRow, error) {
	row := q.db.QueryRow(ctx, sessionGetByID, id)
	var i SessionGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionListActiveByRange = `-- name: SessionListActiveByRange :many
SELECT id, series_id, course_id, room_id, teacher_id, start_at, end_at, version, deleted_at, created_at, updated_at
FROM sessions
WHERE deleted_at IS NULL
  AND start_at < $1
  AND end_at > $2
ORDER BY start_at ASC
`

type SessionListActiveByRangeParams struct {
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
	RangeStart pgtype.Timestamptz `json:"range_start"`
}

type SessionListActiveByRangeRow struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Version   int32              `json:"version"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionListActiveByRange(ctx context.Context, arg SessionListActiveByRangeParams) ([]SessionListActiveByRangeRow, error) {
	rows, err := q.db.Query(ctx, sessionListActiveByRange, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionListActiveByRangeRow
	for rows.Next() {
		var i SessionListActiveByRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.CourseID,
			&i.RoomID,
			&i.TeacherID,
			&i.StartAt,
			&i.EndAt,
			&i.Version,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionListByRange = `-- name: SessionListByRange :many
SELECT id, series_id, course_id, room_id, teacher_id, start_at, end_at, version, deleted_at, created_at, updated_at
FROM sessions
WHERE start_at < $1 AND end_at > $2
ORDER BY start_at ASC
`

type SessionListByRangeParams struct {
	RangeEnd   pgtype.Timestamptz `json:"range_end"`
	RangeStart pgtype.Timestamptz `json:"range_start"`
}

type SessionListByRangeRow struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Version   int32              `json:"version"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionListByRange(ctx context.Context, arg SessionListByRangeParams) ([]SessionListByRangeRow, error) {
	rows, err := q.db.Query(ctx, sessionListByRange, arg.RangeEnd, arg.RangeStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionListByRangeRow
	for rows.Next() {
		var i SessionListByRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.CourseID,
			&i.RoomID,
			&i.TeacherID,
			&i.StartAt,
			&i.EndAt,
			&i.Version,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionLockOverlappingForInsert = `-- name: SessionLockOverlappingForInsert :many
SELECT id FROM sessions
WHERE deleted_at IS NULL
  AND ((teacher_id = $1 AND time_range && tstzrange($2, $3, '[)'))
       OR (room_id = $4 AND time_range && tstzrange($2, $3, '[)')))
FOR UPDATE
`

type SessionLockOverlappingForInsertParams struct {
	TeacherID   pgtype.UUID `json:"teacher_id"`
	Tstzrange   interface{} `json:"tstzrange"`
	Tstzrange_2 interface{} `json:"tstzrange_2"`
	RoomID      pgtype.UUID `json:"room_id"`
}

func (q *Queries) SessionLockOverlappingForInsert(ctx context.Context, arg SessionLockOverlappingForInsertParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, sessionLockOverlappingForInsert,
		arg.TeacherID,
		arg.Tstzrange,
		arg.Tstzrange_2,
		arg.RoomID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionSoftDelete = `-- name: SessionSoftDelete :one
UPDATE sessions
SET deleted_at = now(), updated_at = now(), version = version + 1
WHERE id = $1 AND deleted_at IS NULL AND version = $2
RETURNING 1
`

type SessionSoftDeleteParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) SessionSoftDelete(ctx context.Context, arg SessionSoftDeleteParams) (int32, error) {
	row := q.db.QueryRow(ctx, sessionSoftDelete, arg.ID, arg.Version)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const sessionSoftDeleteFutureBySeries = `-- name: SessionSoftDeleteFutureBySeries :exec
UPDATE sessions
SET deleted_at = now(), updated_at = now(), version = version + 1
WHERE series_id = $1
  AND deleted_at IS NULL
  AND start_at >= $2
`

type SessionSoftDeleteFutureBySeriesParams struct {
	SeriesID pgtype.UUID        `json:"series_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) SessionSoftDeleteFutureBySeries(ctx context.Context, arg SessionSoftDeleteFutureBySeriesParams) error {
	_, err := q.db.Exec(ctx, sessionSoftDeleteFutureBySeries, arg.SeriesID, arg.StartAt)
	return err
}

const sessionSoftDeleteFutureBySeriesCount = `-- name: SessionSoftDeleteFutureBySeriesCount :one
WITH upd AS (
  UPDATE sessions
  SET deleted_at = now(), updated_at = now(), version = version + 1
  WHERE series_id = $1
    AND deleted_at IS NULL
    AND start_at >= $2
  RETURNING 1
)
SELECT count(*)::int4 AS canceled
FROM upd
`

type SessionSoftDeleteFutureBySeriesCountParams struct {
	SeriesID pgtype.UUID        `json:"series_id"`
	StartAt  pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) SessionSoftDeleteFutureBySeriesCount(ctx context.Context, arg SessionSoftDeleteFutureBySeriesCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, sessionSoftDeleteFutureBySeriesCount, arg.SeriesID, arg.StartAt)
	var canceled int32
	err := row.Scan(&canceled)
	return canceled, err
}

const sessionUpdateOccurrence = `-- name: SessionUpdateOccurrence :one
UPDATE sessions
SET course_id = $2,
    room_id = $3,
    teacher_id = $4,
    start_at = $5,
    end_at = $6,
    updated_at = now(),
    version = version + 1
WHERE id = $1 AND version = $7
RETURNING id, series_id, course_id, room_id, teacher_id, start_at, end_at, version, deleted_at, created_at, updated_at
`

type SessionUpdateOccurrenceParams struct {
	ID        pgtype.UUID        `json:"id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Version   int32              `json:"version"`
}

type SessionUpdateOccurrenceRow struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Version   int32              `json:"version"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionUpdateOccurrence(ctx context.Context, arg SessionUpdateOccurrenceParams) (SessionUpdateOccurrenceRow, error) {
	row := q.db.QueryRow(ctx, sessionUpdateOccurrence,
		arg.ID,
		arg.CourseID,
		arg.RoomID,
		arg.TeacherID,
		arg.StartAt,
		arg.EndAt,
		arg.Version,
	)
	var i SessionUpdateOccurrenceRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionUpdateTime = `-- name: SessionUpdateTime :one
UPDATE sessions
SET start_at = $2, end_at = $3, updated_at = now(), version = version + 1
WHERE id = $1 AND version = $4
RETURNING id, series_id, course_id, room_id, teacher_id, start_at, end_at, version, deleted_at, created_at, updated_at
`

type SessionUpdateTimeParams struct {
	ID      pgtype.UUID        `json:"id"`
	StartAt pgtype.Timestamptz `json:"start_at"`
	EndAt   pgtype.Timestamptz `json:"end_at"`
	Version int32              `json:"version"`
}

type SessionUpdateTimeRow struct {
	ID        pgtype.UUID        `json:"id"`
	SeriesID  pgtype.UUID        `json:"series_id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	TeacherID pgtype.UUID        `json:"teacher_id"`
	StartAt   pgtype.Timestamptz `json:"start_at"`
	EndAt     pgtype.Timestamptz `json:"end_at"`
	Version   int32              `json:"version"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionUpdateTime(ctx context.Context, arg SessionUpdateTimeParams) (SessionUpdateTimeRow, error) {
	row := q.db.QueryRow(ctx, sessionUpdateTime,
		arg.ID,
		arg.StartAt,
		arg.EndAt,
		arg.Version,
	)
	var i SessionUpdateTimeRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.CourseID,
		&i.RoomID,
		&i.TeacherID,
		&i.StartAt,
		&i.EndAt,
		&i.Version,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentBusyRangesLockOverlapping = `-- name: StudentBusyRangesLockOverlapping :many
SELECT id FROM student_busy_ranges
WHERE deleted_at IS NULL
  AND student_id = ANY($1::uuid[])
  AND time_range && tstzrange($2, $3, '[)')
FOR UPDATE
`

type StudentBusyRangesLockOverlappingParams struct {
	Column1     []pgtype.UUID `json:"column_1"`
	Tstzrange   interface{}   `json:"tstzrange"`
	Tstzrange_2 interface{}   `json:"tstzrange_2"`
}

func (q *Queries) StudentBusyRangesLockOverlapping(ctx context.Context, arg StudentBusyRangesLockOverlappingParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, studentBusyRangesLockOverlapping, arg.Column1, arg.Tstzrange, arg.Tstzrange_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
