// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const studentCreate = `-- name: StudentCreate :one
INSERT INTO students (wcode, full_name, notes)
VALUES ($1, $2, $3)
ON CONFLICT (wcode) DO UPDATE
SET full_name = EXCLUDED.full_name,
    notes = CASE WHEN EXCLUDED.notes = '' THEN students.notes ELSE EXCLUDED.notes END,
    updated_at = now()
RETURNING id, wcode, full_name, notes, created_at, updated_at
`

type StudentCreateParams struct {
	Wcode    string `json:"wcode"`
	FullName string `json:"full_name"`
	Notes    string `json:"notes"`
}

type StudentCreateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentCreate(ctx context.Context, arg StudentCreateParams) (StudentCreateRow, error) {
	row := q.db.QueryRow(ctx, studentCreate, arg.Wcode, arg.FullName, arg.Notes)
	var i StudentCreateRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentFindDuplicates = `-- name: StudentFindDuplicates :many
SELECT wcode, COUNT(*) AS cnt
FROM students
GROUP BY wcode
HAVING COUNT(*) > 1
ORDER BY cnt DESC
`

type StudentFindDuplicatesRow struct {
	Wcode string `json:"wcode"`
	Cnt   int64  `json:"cnt"`
}

func (q *Queries) StudentFindDuplicates(ctx context.Context) ([]StudentFindDuplicatesRow, error) {
	rows, err := q.db.Query(ctx, studentFindDuplicates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentFindDuplicatesRow
	for rows.Next() {
		var i StudentFindDuplicatesRow
		if err := rows.Scan(&i.Wcode, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentGetByID = `-- name: StudentGetByID :one
SELECT id, wcode, full_name, notes, created_at, updated_at
FROM students
WHERE id = $1
`

type StudentGetByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentGetByID(ctx context.Context, id pgtype.UUID) (StudentGetByIDRow, error) {
	row := q.db.QueryRow(ctx, studentGetByID, id)
	var i StudentGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentGetByWCode = `-- name: StudentGetByWCode :one
SELECT id, wcode, full_name, notes, created_at, updated_at
FROM students
WHERE wcode = $1
`

type StudentGetByWCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentGetByWCode(ctx context.Context, wcode string) (StudentGetByWCodeRow, error) {
	row := q.db.QueryRow(ctx, studentGetByWCode, wcode)
	var i StudentGetByWCodeRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentList = `-- name: StudentList :many
SELECT id, wcode, full_name, notes, created_at, updated_at
FROM students
WHERE (wcode ILIKE '%' || $3 || '%' OR full_name ILIKE '%' || $3 || '%' OR $3 = '')
ORDER BY wcode ASC
LIMIT $1 OFFSET $2
`

type StudentListParams struct {
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Column3 pgtype.Text `json:"column_3"`
}

type StudentListRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentList(ctx context.Context, arg StudentListParams) ([]StudentListRow, error) {
	rows, err := q.db.Query(ctx, studentList, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentListRow
	for rows.Next() {
		var i StudentListRow
		if err := rows.Scan(
			&i.ID,
			&i.Wcode,
			&i.FullName,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentListCount = `-- name: StudentListCount :one
SELECT count(*) FROM students
WHERE (wcode ILIKE '%' || $1 || '%' OR full_name ILIKE '%' || $1 || '%' OR $1 = '')
`

func (q *Queries) StudentListCount(ctx context.Context, dollar_1 pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, studentListCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const studentUpdate = `-- name: StudentUpdate :one
UPDATE students
SET wcode = $2, full_name = $3, notes = $4, updated_at = now()
WHERE students.id = $1
  AND ($2 = (SELECT s2.wcode FROM students s2 WHERE s2.id = $1)
       OR NOT EXISTS (SELECT 1 FROM students s3 WHERE s3.wcode = $2 AND s3.id <> $1))
RETURNING students.id, students.wcode, students.full_name, students.notes, students.created_at, students.updated_at
`

type StudentUpdateParams struct {
	ID       pgtype.UUID `json:"id"`
	Wcode    string      `json:"wcode"`
	FullName string      `json:"full_name"`
	Notes    string      `json:"notes"`
}

type StudentUpdateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentUpdate(ctx context.Context, arg StudentUpdateParams) (StudentUpdateRow, error) {
	row := q.db.QueryRow(ctx, studentUpdate,
		arg.ID,
		arg.Wcode,
		arg.FullName,
		arg.Notes,
	)
	var i StudentUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentUpsertNameByWCode = `-- name: StudentUpsertNameByWCode :one
INSERT INTO students (wcode, full_name, notes)
VALUES ($1, $2, '')
ON CONFLICT (wcode) DO UPDATE
SET full_name = EXCLUDED.full_name,
    updated_at = now()
RETURNING id, wcode, full_name, notes, created_at, updated_at
`

type StudentUpsertNameByWCodeParams struct {
	Wcode    string `json:"wcode"`
	FullName string `json:"full_name"`
}

type StudentUpsertNameByWCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentUpsertNameByWCode(ctx context.Context, arg StudentUpsertNameByWCodeParams) (StudentUpsertNameByWCodeRow, error) {
	row := q.db.QueryRow(ctx, studentUpsertNameByWCode, arg.Wcode, arg.FullName)
	var i StudentUpsertNameByWCodeRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
