// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const studentCreate = `-- name: StudentCreate :one
INSERT INTO students (wcode, full_name, notes)
VALUES ($1, $2, $3)
RETURNING id, wcode, full_name, notes, created_at, updated_at
`

type StudentCreateParams struct {
	Wcode    string `json:"wcode"`
	FullName string `json:"full_name"`
	Notes    string `json:"notes"`
}

type StudentCreateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentCreate(ctx context.Context, arg StudentCreateParams) (StudentCreateRow, error) {
	row := q.db.QueryRow(ctx, studentCreate, arg.Wcode, arg.FullName, arg.Notes)
	var i StudentCreateRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentGetByID = `-- name: StudentGetByID :one
SELECT id, wcode, full_name, notes, created_at, updated_at
FROM students
WHERE id = $1
`

type StudentGetByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentGetByID(ctx context.Context, id pgtype.UUID) (StudentGetByIDRow, error) {
	row := q.db.QueryRow(ctx, studentGetByID, id)
	var i StudentGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentGetByWCode = `-- name: StudentGetByWCode :one
SELECT id, wcode, full_name, notes, created_at, updated_at
FROM students
WHERE wcode = $1
`

type StudentGetByWCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentGetByWCode(ctx context.Context, wcode string) (StudentGetByWCodeRow, error) {
	row := q.db.QueryRow(ctx, studentGetByWCode, wcode)
	var i StudentGetByWCodeRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentList = `-- name: StudentList :many
SELECT id, wcode, full_name, notes, created_at, updated_at
FROM students
ORDER BY wcode ASC
LIMIT $1 OFFSET $2
`

type StudentListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type StudentListRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentList(ctx context.Context, arg StudentListParams) ([]StudentListRow, error) {
	rows, err := q.db.Query(ctx, studentList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudentListRow
	for rows.Next() {
		var i StudentListRow
		if err := rows.Scan(
			&i.ID,
			&i.Wcode,
			&i.FullName,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const studentUpdate = `-- name: StudentUpdate :one
UPDATE students
SET wcode = $2, full_name = $3, notes = $4, updated_at = now()
WHERE id = $1
RETURNING id, wcode, full_name, notes, created_at, updated_at
`

type StudentUpdateParams struct {
	ID       pgtype.UUID `json:"id"`
	Wcode    string      `json:"wcode"`
	FullName string      `json:"full_name"`
	Notes    string      `json:"notes"`
}

type StudentUpdateRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentUpdate(ctx context.Context, arg StudentUpdateParams) (StudentUpdateRow, error) {
	row := q.db.QueryRow(ctx, studentUpdate,
		arg.ID,
		arg.Wcode,
		arg.FullName,
		arg.Notes,
	)
	var i StudentUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const studentUpsertNameByWCode = `-- name: StudentUpsertNameByWCode :one
INSERT INTO students (wcode, full_name, notes)
VALUES ($1, $2, '')
ON CONFLICT (wcode) DO UPDATE
SET full_name = EXCLUDED.full_name,
    updated_at = now()
RETURNING id, wcode, full_name, notes, created_at, updated_at
`

type StudentUpsertNameByWCodeParams struct {
	Wcode    string `json:"wcode"`
	FullName string `json:"full_name"`
}

type StudentUpsertNameByWCodeRow struct {
	ID        pgtype.UUID        `json:"id"`
	Wcode     string             `json:"wcode"`
	FullName  string             `json:"full_name"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StudentUpsertNameByWCode(ctx context.Context, arg StudentUpsertNameByWCodeParams) (StudentUpsertNameByWCodeRow, error) {
	row := q.db.QueryRow(ctx, studentUpsertNameByWCode, arg.Wcode, arg.FullName)
	var i StudentUpsertNameByWCodeRow
	err := row.Scan(
		&i.ID,
		&i.Wcode,
		&i.FullName,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
