// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subjects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const subjectCreate = `-- name: SubjectCreate :one
INSERT INTO subjects (code, name)
VALUES ($1, $2)
RETURNING id, code, name, deleted_at, created_at, updated_at
`

type SubjectCreateParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) SubjectCreate(ctx context.Context, arg SubjectCreateParams) (Subject, error) {
	row := q.db.QueryRow(ctx, subjectCreate, arg.Code, arg.Name)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const subjectGetByID = `-- name: SubjectGetByID :one
SELECT id, code, name, deleted_at, created_at, updated_at
FROM subjects
WHERE id = $1
`

func (q *Queries) SubjectGetByID(ctx context.Context, id pgtype.UUID) (Subject, error) {
	row := q.db.QueryRow(ctx, subjectGetByID, id)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const subjectListActive = `-- name: SubjectListActive :many
SELECT id, code, name, deleted_at, created_at, updated_at
FROM subjects
WHERE deleted_at IS NULL
ORDER BY code ASC
`

func (q *Queries) SubjectListActive(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, subjectListActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subjectSoftDelete = `-- name: SubjectSoftDelete :exec
UPDATE subjects
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SubjectSoftDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, subjectSoftDelete, id)
	return err
}
