// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userListByRoleActive = `-- name: UserListByRoleActive :many
SELECT id, username, role, deleted_at, created_at, updated_at
FROM users
WHERE deleted_at IS NULL
  AND role = $1
ORDER BY username ASC
`

type UserListByRoleActiveRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Role      string             `json:"role"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UserListByRoleActive(ctx context.Context, role string) ([]UserListByRoleActiveRow, error) {
	rows, err := q.db.Query(ctx, userListByRoleActive, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserListByRoleActiveRow
	for rows.Next() {
		var i UserListByRoleActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
